//HintName: StoreInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class StoreInstrumented : IStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.Store");
    private static readonly Meter _meter = new("MyApp.Store");

    private readonly IStore _inner;
    private readonly string _spanName_SaveAsync_0;
    private readonly string _spanName_LoadAsync_1;
    public StoreInstrumented(IStore inner)
    {
        _inner = inner;
        // Composed once per wrapped instance. Doing it per call would allocate a
        // string on every invocation of an instrumented method.
        var _implName = inner.GetType().Name;
        _spanName_SaveAsync_0 = _implName + ".save";
        _spanName_LoadAsync_1 = "a." + _implName + ".b." + _implName + ".c";
    }

    public async global::System.Threading.Tasks.Task SaveAsync()
    {
        using var _activity = _activitySource.StartActivity(_spanName_SaveAsync_0);
        try
        {
            await _inner.SaveAsync();
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task LoadAsync()
    {
        using var _activity = _activitySource.StartActivity(_spanName_LoadAsync_1);
        try
        {
            await _inner.LoadAsync();
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
