//HintName: SharedServiceInstrumented.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

public sealed class SharedServiceInstrumented : ISharedService
{
    private static readonly ActivitySource _activitySource = new("MyApp.Shared");
    private static readonly Meter _meter = new("MyApp.Shared");

    private readonly ISharedService _inner;
    public SharedServiceInstrumented(ISharedService inner) => _inner = inner;

    public async global::System.Threading.Tasks.ValueTask RunAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("shared.run");
        try
        {
            await _inner.RunAsync(ct);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
