//HintName: VectorStoreInstrumented.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class VectorStoreInstrumented : IVectorStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.VectorStore");
    private static readonly Meter _meter = new("MyApp.VectorStore");

    private readonly IVectorStore _inner;
    public VectorStoreInstrumented(IVectorStore inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> SearchAsync(string collection, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("vectorstore.search");
        try
        {
            var _result = await _inner.SearchAsync(collection, ct);
            var _tagged = _result;
            _activity?.SetTag("vectorstore.result.count", _tagged?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
