//HintName: PathsInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PathsInstrumented : IPaths
{
    private static readonly ActivitySource _activitySource = new("MyApp.Paths");
    private static readonly Meter _meter = new("MyApp.Paths");

    private readonly IPaths _inner;
    public PathsInstrumented(IPaths inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::Outer> DeepAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("paths.deep");
        try
        {
            var _result = await _inner.DeepAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("deep.count", _tagged?.Inner?.Items?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<global::Outer> ValueAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("paths.value");
        try
        {
            var _result = await _inner.ValueAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("value.total", _tagged?.Total);
            _activity?.SetTag("value.width", _tagged?.Extent.Width);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
