//HintName: GraphInstrumented.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class GraphInstrumented : IGraph
{
    private static readonly ActivitySource _activitySource = new("MyApp.Graph");
    private static readonly Meter _meter = new("MyApp.Graph");

    private readonly IGraph _inner;
    public GraphInstrumented(IGraph inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::System.ReadOnlyMemory<byte>> ClusterAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("graph.cluster");
        try
        {
            var _result = await _inner.ClusterAsync(ct);
            _activity?.SetTag("graph.community.count", _result.Length);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int?> CountAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("graph.count");
        try
        {
            var _result = await _inner.CountAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("graph.node.count", _tagged?.Value);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
