//HintName: VectorStoreInstrumented.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class VectorStoreInstrumented : IVectorStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.VectorStore");
    private static readonly Meter _meter = new("MyApp.VectorStore");

    private readonly IVectorStore _inner;
    public VectorStoreInstrumented(IVectorStore inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> SearchAsync(string collection, int topK, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("vectorstore.search");
        _activity?.SetTag("vectorstore.collection", collection);
        _activity?.SetTag("top.k", topK);
        try
        {
            var _result = await _inner.SearchAsync(collection, topK, ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
