//HintName: OrderServiceInstrumented.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrderServiceInstrumented : IOrderService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Counter<long> _orders_created = _meter.CreateCounter<long>("orders.created");

    private readonly IOrderService _inner;
    public OrderServiceInstrumented(IOrderService inner) => _inner = inner;

    public async global::System.Threading.Tasks.ValueTask CreateOrderAsync(string orderId, global::System.Threading.CancellationToken ct)
    {
        try
        {
            await _inner.CreateOrderAsync(orderId, ct);
            _orders_created.Add(1);
        }
        catch (Exception _ex)
        {
            throw;
        }
    }
}
