//HintName: SpansInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class SpansInstrumented : ISpans
{
    private static readonly ActivitySource _activitySource = new("MyApp.Spans");
    private static readonly Meter _meter = new("MyApp.Spans");

    private readonly ISpans _inner;
    public SpansInstrumented(ISpans inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task TakeAsync(global::System.ReadOnlyMemory<byte> buffer, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("spans.take");
        _activity?.SetTag("span.length", buffer.Length);
        try
        {
            await _inner.TakeAsync(buffer, ct);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
