//HintName: IChat.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ChatInstrumented : IChat
{
    private static readonly ActivitySource _activitySource = new("gen_ai");
    private static readonly Meter _meter = new("gen_ai");
    private static readonly Histogram<double> _gen_ai_client_operation_duration = _meter.CreateHistogram<double>("gen_ai.client.operation.duration", unit: "s", description: null, tags: null, advice: new InstrumentAdvice<double> { HistogramBucketBoundaries = new double[] { 0.01, 0.1, 1, 10 } });
    private static readonly Histogram<double> _gen_ai_latency = _meter.CreateHistogram<double>("gen_ai.latency", unit: "s");
    private static readonly Histogram<double> _gen_ai_score = _meter.CreateHistogram<double>("gen_ai.score");

    private readonly IChat _inner;
    public ChatInstrumented(IChat inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<global::Reply> CompleteAsync(string model, global::System.Threading.CancellationToken ct)
    {
        if (!_gen_ai_client_operation_duration.Enabled && !_gen_ai_latency.Enabled && !_gen_ai_score.Enabled)
        {
            try
            {
                return _inner.CompleteAsync(model, ct);
            }
            catch (Exception _ex)
            {
                return _fault_CompleteAsync_0(_ex);
            }
        }
        return _core_CompleteAsync_0(model, ct);
    }

    private async global::System.Threading.Tasks.ValueTask<global::Reply> _core_CompleteAsync_0(string model, global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CompleteAsync(model, ct);
            if (_gen_ai_latency.Enabled)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("gen_ai.operation.name", "chat");
                if (model is { } _metricTag0_1)
                    _metricTags0.Add("gen_ai.request.model", _metricTag0_1);
                _recordEach(_gen_ai_latency, _result.Usage.Latencies.Span, in _metricTags0);
            }
            if (_gen_ai_score.Enabled && _result.Usage.Scores is { } _read1)
            {
                var _metricTags1 = new TagList();
                _metricTags1.Add("gen_ai.operation.name", "chat");
                if (model is { } _metricTag1_1)
                    _metricTags1.Add("gen_ai.request.model", _metricTag1_1);
                foreach (var _each1 in _read1)
                    _gen_ai_score.Record(_each1, in _metricTags1);
            }
            if (_gen_ai_client_operation_duration.Enabled)
            {
                var _metricTags2 = new TagList();
                _metricTags2.Add("gen_ai.operation.name", "chat");
                if (model is { } _metricTag2_1)
                    _metricTags2.Add("gen_ai.request.model", _metricTag2_1);
                _gen_ai_client_operation_duration.Record(Stopwatch.GetElapsedTime(_sw).TotalSeconds, in _metricTags2);
            }
            return _result;
        }
        catch (Exception)
        {
            if (_gen_ai_client_operation_duration.Enabled)
            {
                var _metricTags3 = new TagList();
                _metricTags3.Add("gen_ai.operation.name", "chat");
                if (model is { } _metricTag3_1)
                    _metricTags3.Add("gen_ai.request.model", _metricTag3_1);
                _gen_ai_client_operation_duration.Record(Stopwatch.GetElapsedTime(_sw).TotalSeconds, in _metricTags3);
            }
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask<global::Reply> _fault_CompleteAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    private static void _recordEach(Histogram<double> histogram, ReadOnlySpan<double> values)
    {
        foreach (ref readonly var value in values)
            histogram.Record(value);
    }

    private static void _recordEach(Histogram<double> histogram, ReadOnlySpan<double> values, in TagList tags)
    {
        foreach (ref readonly var value in values)
            histogram.Record(value, in tags);
    }
}
