//HintName: IFields.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class FieldsInstrumented : IFields
{
    private static readonly ActivitySource _activitySource = new("MyApp.Fields");
    private static readonly Meter _meter = new("MyApp.Fields");
    private static readonly Counter<long> _x = _meter.CreateCounter<long>("x");
    private static readonly Histogram<double> _x_2 = _meter.CreateHistogram<double>("x");
    private static readonly Counter<long> _a_b = _meter.CreateCounter<long>("a.b");
    private static readonly Counter<long> _a_b_2 = _meter.CreateCounter<long>("a_b");
    private static readonly Counter<long> _http_requests_total = _meter.CreateCounter<long>("http/requests total");
    private static readonly Counter<long> _say__hi_ = _meter.CreateCounter<long>("say \"hi\"");
    private static readonly Counter<long> _metric_meter = _meter.CreateCounter<long>("meter");
    private static readonly Histogram<double> _metric_result = _meter.CreateHistogram<double>("result");

    private readonly IFields _inner;
    public FieldsInstrumented(IFields inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<int> CountedAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_x.Enabled)
        {
            try
            {
                return _inner.CountedAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_CountedAsync_0(_ex);
            }
        }
        return _core_CountedAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_CountedAsync_0(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.CountedAsync(ct);
            _x.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_CountedAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> TimedAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_x_2.Enabled)
        {
            try
            {
                return _inner.TimedAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_TimedAsync_1(_ex);
            }
        }
        return _core_TimedAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_TimedAsync_1(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.TimedAsync(ct);
            _x_2.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _x_2.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_TimedAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> DottedAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_a_b.Enabled)
        {
            try
            {
                return _inner.DottedAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_DottedAsync_2(_ex);
            }
        }
        return _core_DottedAsync_2(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_DottedAsync_2(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.DottedAsync(ct);
            _a_b.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_DottedAsync_2(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> UnderscoredAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_a_b_2.Enabled)
        {
            try
            {
                return _inner.UnderscoredAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_UnderscoredAsync_3(_ex);
            }
        }
        return _core_UnderscoredAsync_3(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_UnderscoredAsync_3(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.UnderscoredAsync(ct);
            _a_b_2.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_UnderscoredAsync_3(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> SlashAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_http_requests_total.Enabled)
        {
            try
            {
                return _inner.SlashAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_SlashAsync_4(_ex);
            }
        }
        return _core_SlashAsync_4(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_SlashAsync_4(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.SlashAsync(ct);
            _http_requests_total.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_SlashAsync_4(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> QuotedAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_say__hi_.Enabled)
        {
            try
            {
                return _inner.QuotedAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_QuotedAsync_5(_ex);
            }
        }
        return _core_QuotedAsync_5(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_QuotedAsync_5(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.QuotedAsync(ct);
            _say__hi_.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_QuotedAsync_5(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> MeterAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_metric_meter.Enabled)
        {
            try
            {
                return _inner.MeterAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_MeterAsync_6(_ex);
            }
        }
        return _core_MeterAsync_6(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_MeterAsync_6(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.MeterAsync(ct);
            _metric_meter.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_MeterAsync_6(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> ResultAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_metric_result.Enabled)
        {
            try
            {
                return _inner.ResultAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_ResultAsync_7(_ex);
            }
        }
        return _core_ResultAsync_7(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_ResultAsync_7(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.ResultAsync(ct);
            _metric_result.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _metric_result.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_ResultAsync_7(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> CountedAgainAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_x.Enabled)
        {
            try
            {
                return _inner.CountedAgainAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_CountedAgainAsync_8(_ex);
            }
        }
        return _core_CountedAgainAsync_8(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_CountedAgainAsync_8(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.CountedAgainAsync(ct);
            _x.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_CountedAgainAsync_8(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
