//HintName: IFields.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class FieldsInstrumented : IFields
{
    private static readonly ActivitySource _activitySource = new("MyApp.Fields");
    private static readonly Meter _meter = new("MyApp.Fields");
    private static readonly Counter<long> _x = _meter.CreateCounter<long>("x");
    private static readonly Histogram<double> _x_2 = _meter.CreateHistogram<double>("x");
    private static readonly Counter<long> _a_b = _meter.CreateCounter<long>("a.b");
    private static readonly Counter<long> _a_b_2 = _meter.CreateCounter<long>("a_b");
    private static readonly Counter<long> _http_requests_total = _meter.CreateCounter<long>("http/requests total");
    private static readonly Counter<long> _say__hi_ = _meter.CreateCounter<long>("say \"hi\"");
    private static readonly Counter<long> _metric_meter = _meter.CreateCounter<long>("meter");
    private static readonly Histogram<double> _metric_result = _meter.CreateHistogram<double>("result");

    private readonly IFields _inner;
    public FieldsInstrumented(IFields inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<int> CountedAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.CountedAsync(ct);
            _x.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> TimedAsync(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.TimedAsync(ct);
            _x_2.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _x_2.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> DottedAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.DottedAsync(ct);
            _a_b.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> UnderscoredAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.UnderscoredAsync(ct);
            _a_b_2.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> SlashAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.SlashAsync(ct);
            _http_requests_total.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> QuotedAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.QuotedAsync(ct);
            _say__hi_.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> MeterAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.MeterAsync(ct);
            _metric_meter.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> ResultAsync(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.ResultAsync(ct);
            _metric_result.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _metric_result.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> CountedAgainAsync(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.CountedAgainAsync(ct);
            _x.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }
}
