//HintName: OrdersInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrdersInstrumented : IOrders
{
    private static readonly ActivitySource _activitySource = new("MyApp.Orders");
    private static readonly Meter _meter = new("MyApp.Orders");
    private static readonly Counter<long> _orders_created = _meter.CreateCounter<long>("orders.created", unit: "{order}", description: "Orders accepted for fulfilment");
    private static readonly Histogram<double> _order_create_ms = _meter.CreateHistogram<double>("order.create_ms", unit: "ms", description: "Time to create an order");

    private readonly IOrders _inner;
    public OrdersInstrumented(IOrders inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<int> CreateAsync(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CreateAsync(ct);
            _orders_created.Add(1);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<int> CreateAgainAsync(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CreateAgainAsync(ct);
            _orders_created.Add(1);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }
}
