//HintName: IQuotes.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class QuotesInstrumented : IQuotes
{
    private static readonly ActivitySource _activitySource = new("MyApp.Quotes");
    private static readonly Meter _meter = new("MyApp.Quotes");
    private static readonly Histogram<double> _quote_cost = _meter.CreateHistogram<double>("quote.cost");
    private static readonly Counter<long> _status_calls = _meter.CreateCounter<long>("status.calls");

    private readonly IQuotes _inner;
    public QuotesInstrumented(IQuotes inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<global::Quote> QuoteAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_quote_cost.Enabled)
            return _inner.QuoteAsync(ct);
        return _core_QuoteAsync_0(ct);
    }

    private async global::System.Threading.Tasks.ValueTask<global::Quote> _core_QuoteAsync_0(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.QuoteAsync(ct);
            if (_quote_cost.Enabled && _result.Priced)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("quote.region", _result.Region);
                if (_result.Priced && _result.Currency is { } _metricTag0_1)
                    _metricTags0.Add("quote.currency", _metricTag0_1);
                _quote_cost.Record((double)_result.Cost, in _metricTags0);
            }
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public string Status()
    {
        try
        {
            var _result = _inner.Status();
            var _tagged = _result;
            if (_status_calls.Enabled)
            {
                var _metricTags0 = new TagList();
                if (_tagged is { } _metricTag0_0)
                    _metricTags0.Add("status", _metricTag0_0);
                _status_calls.Add(1, in _metricTags0);
            }
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }
}
