//HintName: IOrders.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrdersInstrumented : IOrders
{
    private static readonly ActivitySource _activitySource = new("MyApp.Orders");
    private static readonly Meter _meter = new("MyApp.Orders");
    private static readonly Counter<long> _orders_created = _meter.CreateCounter<long>("orders.created", unit: "{order}", description: "Orders accepted for fulfilment");
    private static readonly Histogram<double> _order_create_ms = _meter.CreateHistogram<double>("order.create_ms", unit: "ms", description: "Time to create an order");

    private readonly IOrders _inner;
    public OrdersInstrumented(IOrders inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<int> CreateAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_orders_created.Enabled && !_order_create_ms.Enabled)
        {
            try
            {
                return _inner.CreateAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_CreateAsync_0(_ex);
            }
        }
        return _core_CreateAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_CreateAsync_0(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CreateAsync(ct).ConfigureAwait(false);
            _orders_created.Add(1);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            if (_order_create_ms.Enabled)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("error.type", _ex.GetType().FullName);
                _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds, in _metricTags0);
            }
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_CreateAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int> CreateAgainAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_orders_created.Enabled && !_order_create_ms.Enabled)
        {
            try
            {
                return _inner.CreateAgainAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_CreateAgainAsync_1(_ex);
            }
        }
        return _core_CreateAgainAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_CreateAgainAsync_1(global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CreateAgainAsync(ct).ConfigureAwait(false);
            _orders_created.Add(1);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            if (_order_create_ms.Enabled)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("error.type", _ex.GetType().FullName);
                _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds, in _metricTags0);
            }
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int> _fault_CreateAgainAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
