//HintName: ChatInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ChatInstrumented : IChat
{
    private static readonly ActivitySource _activitySource = new("MyApp.Llm");
    private static readonly Meter _meter = new("MyApp.Llm");
    private static readonly Counter<long> _llm_calls = _meter.CreateCounter<long>("llm.calls");
    private static readonly Histogram<double> _llm_duration = _meter.CreateHistogram<double>("llm.duration");
    private static readonly Counter<long> _llm_tokens_input = _meter.CreateCounter<long>("llm.tokens.input");
    private static readonly Histogram<double> _llm_cost = _meter.CreateHistogram<double>("llm.cost");

    private readonly IChat _inner;
    public ChatInstrumented(IChat inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::Result<global::Reply, global::LlmError>> CompleteAsync(string prompt, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("llm.complete");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CompleteAsync(prompt, ct);
            var _tagged = _result;
            if (_llm_tokens_input.Enabled && _tagged?.IsSuccess == true && _tagged?.Value?.Input is { } _read0)
            {
                var _metricTags0 = new TagList();
                if (_tagged?.IsSuccess == true && _tagged?.Value?.Model is { } _metricTag0_0)
                    _metricTags0.Add("gen_ai.response.model", _metricTag0_0);
                _llm_tokens_input.Add(_read0, in _metricTags0);
            }
            if (_llm_cost.Enabled && _tagged?.IsSuccess == true && _tagged?.Value?.Cost is { } _read1)
            {
                var _metricTags1 = new TagList();
                if (_tagged?.IsSuccess == true && _tagged?.Value?.Model is { } _metricTag1_0)
                    _metricTags1.Add("gen_ai.response.model", _metricTag1_0);
                if (_tagged?.IsSuccess == true && _tagged?.Value?.Cached is { } _metricTag1_1)
                    _metricTags1.Add("llm.cached", _metricTag1_1);
                _llm_cost.Record((double)_read1, in _metricTags1);
            }
            if (_llm_calls.Enabled)
            {
                var _metricTags2 = new TagList();
                if (_tagged?.IsSuccess == true && _tagged?.Value?.Model is { } _metricTag2_0)
                    _metricTags2.Add("gen_ai.response.model", _metricTag2_0);
                _llm_calls.Add(1, in _metricTags2);
            }
            if (_llm_duration.Enabled)
            {
                var _metricTags3 = new TagList();
                if (_tagged?.IsSuccess == true && _tagged?.Value?.Model is { } _metricTag3_0)
                    _metricTags3.Add("gen_ai.response.model", _metricTag3_0);
                _llm_duration.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds, in _metricTags3);
            }
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            _llm_duration.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }
}
