//HintName: Jev.IJevOperations.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Jev;

internal sealed class JevOperationsInstrumented : IJevOperations
{
    private static readonly ActivitySource _activitySource = new("ZeroAlloc.Jev");
    private static readonly Meter _meter = new("ZeroAlloc.Jev");

    private readonly IJevOperations _inner;
    public JevOperationsInstrumented(IJevOperations inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<int> AskAsync(global::System.Uri endpoint, global::Jev.AskRequest request, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.AskAsync(endpoint, request, ct);
            }
            catch (Exception _ex)
            {
                return _fault_AskAsync_0(_ex);
            }
        }
        return _core_AskAsync_0(endpoint, request, ct);
    }

    private async global::System.Threading.Tasks.ValueTask<int> _core_AskAsync_0(global::System.Uri endpoint, global::Jev.AskRequest request, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.HasListeners()
            ? _activitySource.StartActivity("ask", ActivityKind.Internal, default(ActivityContext), _startTags_AskAsync_0(endpoint, request, ct))
            : null;
        try
        {
            var _result = await _inner.AskAsync(endpoint, request, ct).ConfigureAwait(false);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask<int> _fault_AskAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    private static TagList _startTags_AskAsync_0(global::System.Uri endpoint, global::Jev.AskRequest request, global::System.Threading.CancellationToken ct)
    {
        var _startTags = new TagList();
        if (endpoint?.Host is { } _startTag0)
            _startTags.Add("server.address", _startTag0);
        if (endpoint?.Port is { } _startTag1)
            _startTags.Add("server.port", _startTag1);
        if (request?.Model is { } _startTag2)
            _startTags.Add("gen_ai.request.model", _startTag2);
        if (request?.Questions?.Count is { } _startTag3)
            _startTags.Add("jev.question.count", _startTag3);
        return _startTags;
    }
}
