//HintName: App.Holder`1+Api`1+IFoo`1.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace App;

partial struct Holder<T>
{
partial class Api<U>
{
public sealed class FooInstrumented<V> : IFoo<V>
    where V : class
{
    private static readonly ActivitySource _activitySource = new("x");
    private static readonly Meter _meter = new("x");

    private readonly IFoo<V> _inner;
    public FooInstrumented(IFoo<V> inner) => _inner = inner;

    public V? Get(T t, U u)
    {
        using var _activity = _activitySource.StartActivity("get");
        try
        {
            var _result = _inner.Get(t, u);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
}
}
