//HintName: OrderRepositoryInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrderRepositoryInstrumented : IOrderRepository
{
    private static readonly ActivitySource _activitySource = new("MyApp.Orders");
    private static readonly Meter _meter = new("MyApp.Orders");

    private readonly IOrderRepository _inner;
    public OrderRepositoryInstrumented(IOrderRepository inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::OrderRow?> GetByIdAsync(int id, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("orders.get_by_id");
        try
        {
            var _result = await _inner.GetByIdAsync(id, ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<global::OrderRow> FindAsync(string? filter, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("orders.find");
        try
        {
            var _result = await _inner.FindAsync(filter, ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<global::OrderRow?> SearchAsync(string? term, string tenant, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("orders.search");
        try
        {
            var _result = await _inner.SearchAsync(term, tenant, ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
