//HintName: IPlain.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PlainInstrumented : IPlain
{
    private static readonly ActivitySource _activitySource = new("MyApp.Plain");
    private static readonly Meter _meter = new("MyApp.Plain");
    private static readonly Histogram<double> _quote_cost = _meter.CreateHistogram<double>("quote.cost");
    private static readonly Histogram<double> _search_hits = _meter.CreateHistogram<double>("search.hits");
    private static readonly Counter<long> _batch_items = _meter.CreateCounter<long>("batch.items");
    private static readonly Counter<long> _maybe_items = _meter.CreateCounter<long>("maybe.items");

    private readonly IPlain _inner;
    public PlainInstrumented(IPlain inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<global::Quote> QuoteAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_quote_cost.Enabled)
            return _inner.QuoteAsync(ct);
        return _core_QuoteAsync_0(ct);
    }

    private async global::System.Threading.Tasks.ValueTask<global::Quote> _core_QuoteAsync_0(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.QuoteAsync(ct);
            if (_result.Priced)
                _quote_cost.Record((double)_result.Cost);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public global::System.Threading.Tasks.Task<global::SearchPage> SearchAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_search_hits.Enabled)
            return _inner.SearchAsync(ct);
        return _core_SearchAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<global::SearchPage> _core_SearchAsync_1(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.SearchAsync(ct);
            var _tagged = _result;
            if (_tagged?.Hits is { } _read0)
                _search_hits.Record(_read0);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public global::System.Threading.Tasks.Task<int> BatchAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_batch_items.Enabled)
            return _inner.BatchAsync(ct);
        return _core_BatchAsync_2(ct);
    }

    private async global::System.Threading.Tasks.Task<int> _core_BatchAsync_2(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.BatchAsync(ct);
            _batch_items.Add(_result);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }

    public global::System.Threading.Tasks.Task<int?> MaybeAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_maybe_items.Enabled)
            return _inner.MaybeAsync(ct);
        return _core_MaybeAsync_3(ct);
    }

    private async global::System.Threading.Tasks.Task<int?> _core_MaybeAsync_3(global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.MaybeAsync(ct);
            var _tagged = _result;
            if (_tagged is { } _read0)
                _maybe_items.Add(_read0);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }
}
