//HintName: IChat.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ChatInstrumented : IChat
{
    private static readonly ActivitySource _activitySource = new("MyApp.Llm");
    private static readonly Meter _meter = new("MyApp.Llm");
    private static readonly Counter<long> _llm_tokens_input = _meter.CreateCounter<long>("llm.tokens.input", unit: "{token}", description: "Prompt tokens consumed");
    private static readonly Counter<long> _llm_tokens_output = _meter.CreateCounter<long>("llm.tokens.output", unit: "{token}");
    private static readonly Histogram<double> _llm_cost = _meter.CreateHistogram<double>("llm.cost", unit: "USD", description: "Cost of the call");

    private readonly IChat _inner;
    public ChatInstrumented(IChat inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::Result<global::TokenUsage, global::LlmError>> CompleteAsync(string prompt, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners() && !_llm_tokens_input.Enabled && !_llm_tokens_output.Enabled && !_llm_cost.Enabled)
        {
            try
            {
                return _inner.CompleteAsync(prompt, ct);
            }
            catch (Exception _ex)
            {
                return _fault_CompleteAsync_0(_ex);
            }
        }
        return _core_CompleteAsync_0(prompt, ct);
    }

    private async global::System.Threading.Tasks.Task<global::Result<global::TokenUsage, global::LlmError>> _core_CompleteAsync_0(string prompt, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("llm.complete");
        try
        {
            var _result = await _inner.CompleteAsync(prompt, ct).ConfigureAwait(false);
            var _tagged = _result;
            if (_tagged?.IsSuccess == true)
                _activity?.SetTag("gen_ai.usage.input_tokens", _tagged?.Value?.Input);
            if (_tagged?.IsSuccess == true && _tagged?.Value?.Input is { } _read0)
                _llm_tokens_input.Add(_read0);
            if (_tagged?.IsSuccess == true && _tagged?.Value?.Output is { } _read1)
                _llm_tokens_output.Add(_read1);
            if (_tagged?.IsSuccess == true && _tagged?.Value?.Cost is { } _read2)
                _llm_cost.Record((double)_read2);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::Result<global::TokenUsage, global::LlmError>> _fault_CompleteAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
