//HintName: OrdersInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrdersInstrumented : IOrders
{
    private static readonly ActivitySource _activitySource = new("MyApp.Orders");
    private static readonly Meter _meter = new("MyApp.Orders");
    private static readonly Counter<long> _orders_accepted = _meter.CreateCounter<long>("orders.accepted");
    private static readonly Histogram<double> _orders_accept_ms = _meter.CreateHistogram<double>("orders.accept_ms", unit: "ms");

    private readonly IOrders _inner;
    public OrdersInstrumented(IOrders inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::Result<string, global::OrderError>> AcceptAsync(string orderId, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("orders.accept");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.AcceptAsync(orderId, ct);
            var _tagged = _result;
            if (_tagged?.IsSuccess == true)
                _orders_accepted.Add(1);
            if (_tagged?.IsSuccess == true)
                _orders_accept_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
