//HintName: IStore.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class StoreInstrumented : IStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.Store");
    private static readonly Meter _meter = new("MyApp.Store");

    private readonly IStore _inner;
    private readonly string _spanName_SaveAsync_0;
    public StoreInstrumented(IStore inner)
    {
        _inner = inner;
        // Composed once per wrapped instance. Doing it per call would allocate a
        // string on every invocation of an instrumented method.
        var _implName = inner.GetType().Name;
        _spanName_SaveAsync_0 = _implName;
    }

    public global::System.Threading.Tasks.Task SaveAsync()
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.SaveAsync();
            }
            catch (Exception _ex)
            {
                return _fault_SaveAsync_0(_ex);
            }
        }
        return _core_SaveAsync_0();
    }

    private async global::System.Threading.Tasks.Task _core_SaveAsync_0()
    {
        using var _activity = _activitySource.StartActivity(_spanName_SaveAsync_0);
        try
        {
            await _inner.SaveAsync();
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task _fault_SaveAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
    }
}
