//HintName: VectorStoreInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class VectorStoreInstrumented : IVectorStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.VectorStore");
    private static readonly Meter _meter = new("MyApp.VectorStore");

    private readonly IVectorStore _inner;
    private readonly string _spanName_SearchAsync_0;
    public VectorStoreInstrumented(IVectorStore inner)
    {
        _inner = inner;
        // Composed once per wrapped instance. Doing it per call would allocate a
        // string on every invocation of an instrumented method.
        var _implName = inner.GetType().Name;
        _spanName_SearchAsync_0 = "vectorstore.search." + _implName;
    }

    public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> SearchAsync(string collection, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity(_spanName_SearchAsync_0);
        try
        {
            var _result = await _inner.SearchAsync(collection, ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
