//HintName: IStore.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class StoreInstrumented : IStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.Store");
    private static readonly Meter _meter = new("MyApp.Store");

    private readonly IStore _inner;
    private readonly string _spanName_SaveAsync_0;
    private readonly string _spanName_SaveAsync_1;
    public StoreInstrumented(IStore inner)
    {
        _inner = inner;
        // Composed once per wrapped instance. Doing it per call would allocate a
        // string on every invocation of an instrumented method.
        var _implName = inner.GetType().Name;
        _spanName_SaveAsync_0 = "store.save." + _implName;
        _spanName_SaveAsync_1 = "store.save." + _implName;
    }

    public global::System.Threading.Tasks.Task SaveAsync(string key)
    {
        if (!_activitySource.HasListeners())
            return _inner.SaveAsync(key);
        return _core_SaveAsync_0(key);
    }

    private async global::System.Threading.Tasks.Task _core_SaveAsync_0(string key)
    {
        using var _activity = _activitySource.StartActivity(_spanName_SaveAsync_0);
        try
        {
            await _inner.SaveAsync(key);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public global::System.Threading.Tasks.Task SaveAsync(string key, int ttl)
    {
        if (!_activitySource.HasListeners())
            return _inner.SaveAsync(key, ttl);
        return _core_SaveAsync_1(key, ttl);
    }

    private async global::System.Threading.Tasks.Task _core_SaveAsync_1(string key, int ttl)
    {
        using var _activity = _activitySource.StartActivity(_spanName_SaveAsync_1);
        try
        {
            await _inner.SaveAsync(key, ttl);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public global::System.Threading.Tasks.Task PurgeAsync()
    {
        if (!_activitySource.HasListeners())
            return _inner.PurgeAsync();
        return _core_PurgeAsync_2();
    }

    private async global::System.Threading.Tasks.Task _core_PurgeAsync_2()
    {
        using var _activity = _activitySource.StartActivity("store.constant");
        try
        {
            await _inner.PurgeAsync();
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
