//HintName: IExtents.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ExtentsInstrumented : IExtents
{
    private static readonly ActivitySource _activitySource = new("MyApp.Extents");
    private static readonly Meter _meter = new("MyApp.Extents");

    private readonly IExtents _inner;
    public ExtentsInstrumented(IExtents inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::Extent?> WidthAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.WidthAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_WidthAsync_0(_ex);
            }
        }
        return _core_WidthAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<global::Extent?> _core_WidthAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("extents.width");
        try
        {
            var _result = await _inner.WidthAsync(ct).ConfigureAwait(false);
            var _tagged = _result;
            _activity?.SetTag("extent.width", _tagged?.Width);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::Extent?> _fault_WidthAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<bool?> FlagAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.FlagAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_FlagAsync_1(_ex);
            }
        }
        return _core_FlagAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<bool?> _core_FlagAsync_1(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("extents.flag");
        try
        {
            var _result = await _inner.FlagAsync(ct).ConfigureAwait(false);
            var _tagged = _result;
            if (_tagged == true)
                _activity?.SetTag("extent.flag", _result);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<bool?> _fault_FlagAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
