//HintName: IIngest.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class IngestInstrumented : IIngest
{
    private static readonly ActivitySource _activitySource = new("MyApp.Ingest");
    private static readonly Meter _meter = new("MyApp.Ingest");

    private readonly IIngest _inner;
    public IngestInstrumented(IIngest inner) => _inner = inner;

    public global::System.Threading.Tasks.Task StoreAsync(string source, global::System.Collections.Generic.IReadOnlyList<string> chunks, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
            return _inner.StoreAsync(source, chunks, ct);
        return _core_StoreAsync_0(source, chunks, ct);
    }

    private async global::System.Threading.Tasks.Task _core_StoreAsync_0(string source, global::System.Collections.Generic.IReadOnlyList<string> chunks, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("ingest.store");
        _activity?.SetTag("ingest.source", source);
        try
        {
            await _inner.StoreAsync(source, chunks, ct);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
