//HintName: IOutcome.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OutcomeInstrumented : IOutcome
{
    private static readonly ActivitySource _activitySource = new("MyApp.Outcome");
    private static readonly Meter _meter = new("MyApp.Outcome");

    private readonly IOutcome _inner;
    public OutcomeInstrumented(IOutcome inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<global::Outcome> RunAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.RunAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_RunAsync_0(_ex);
            }
        }
        return _core_RunAsync_0(ct);
    }

    private async global::System.Threading.Tasks.ValueTask<global::Outcome> _core_RunAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("outcome.run");
        try
        {
            var _result = await _inner.RunAsync(ct).ConfigureAwait(false);
            if (_result.Ok)
                _activity?.SetTag("outcome.count", _result.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask<global::Outcome> _fault_RunAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
