//HintName: IVectorStore.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class VectorStoreInstrumented : IVectorStore
{
    private static readonly ActivitySource _activitySource = new("MyApp.VectorStore");
    private static readonly Meter _meter = new("MyApp.VectorStore");

    private readonly IVectorStore _inner;
    public VectorStoreInstrumented(IVectorStore inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> SearchAsync(string collection, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.SearchAsync(collection, ct);
            }
            catch (Exception _ex)
            {
                return _fault_SearchAsync_0(_ex);
            }
        }
        return _core_SearchAsync_0(collection, ct);
    }

    private async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> _core_SearchAsync_0(string collection, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("vectorstore.search");
        try
        {
            var _result = await _inner.SearchAsync(collection, ct).ConfigureAwait(false);
            var _tagged = _result;
            _activity?.SetTag("vectorstore.result.count", _tagged?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<string>> _fault_SearchAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
