//HintName: RerankerInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class RerankerInstrumented : IReranker
{
    private static readonly ActivitySource _activitySource = new("MyApp.Rerank");
    private static readonly Meter _meter = new("MyApp.Rerank");

    private readonly IReranker _inner;
    public RerankerInstrumented(IReranker inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::RerankOutcome> RerankAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.run");
        try
        {
            var _result = await _inner.RerankAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("rerank.candidate.count", _tagged?.Candidates);
            _activity?.SetTag("rerank.result.count", _tagged?.Kept);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::System.Threading.Tasks.Task<double> ScoreAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.score");
        try
        {
            var _result = await _inner.ScoreAsync(ct);
            _activity?.SetTag("rerank.score", _result);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
