//HintName: IChat.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ChatInstrumented : IChat
{
    private static readonly ActivitySource _activitySource = new("gen_ai");
    private static readonly Meter _meter = new("gen_ai");

    private readonly IChat _inner;
    public ChatInstrumented(IChat inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<global::ChatResult> ChatAsync(string operation, string model, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.ChatAsync(operation, model, ct);
            }
            catch (Exception _ex)
            {
                return _fault_ChatAsync_0(_ex);
            }
        }
        return _core_ChatAsync_0(operation, model, ct);
    }

    private async global::System.Threading.Tasks.ValueTask<global::ChatResult> _core_ChatAsync_0(string operation, string model, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.HasListeners()
            ? _activitySource.StartActivity("ChatAsync", ActivityKind.Client, default(ActivityContext), _startTags_ChatAsync_0(operation, model, ct))
            : null;
        if (_activity is not null)
        {
            _activity.DisplayName = string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{operation}{" "}{model}");
        }
        try
        {
            var _result = await _inner.ChatAsync(operation, model, ct);
            _activity?.SetTag("gen_ai.response.model", _result.ResponseModel);
            if (_activity is not null && _result.IsFailure)
                _activity.SetStatus(ActivityStatusCode.Error, _result.Error?.Message);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask<global::ChatResult> _fault_ChatAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    private static TagList _startTags_ChatAsync_0(string operation, string model, global::System.Threading.CancellationToken ct)
    {
        var _startTags = new TagList();
        _startTags.Add("gen_ai.provider.name", "openai");
        if (operation is { } _startTag0)
            _startTags.Add("gen_ai.operation.name", _startTag0);
        if (model is { } _startTag1)
            _startTags.Add("gen_ai.request.model", _startTag1);
        return _startTags;
    }
}
