//HintName: IGraph.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class GraphInstrumented : IGraph
{
    private static readonly ActivitySource _activitySource = new("MyApp.Graph");
    private static readonly Meter _meter = new("MyApp.Graph");

    private readonly IGraph _inner;
    public GraphInstrumented(IGraph inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::System.ReadOnlyMemory<byte>> ClusterAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.ClusterAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_ClusterAsync_0(_ex);
            }
        }
        return _core_ClusterAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<global::System.ReadOnlyMemory<byte>> _core_ClusterAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("graph.cluster");
        try
        {
            var _result = await _inner.ClusterAsync(ct).ConfigureAwait(false);
            _activity?.SetTag("graph.community.count", _result.Length);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::System.ReadOnlyMemory<byte>> _fault_ClusterAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<int?> CountAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.CountAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_CountAsync_1(_ex);
            }
        }
        return _core_CountAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<int?> _core_CountAsync_1(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("graph.count");
        try
        {
            var _result = await _inner.CountAsync(ct).ConfigureAwait(false);
            var _tagged = _result;
            _activity?.SetTag("graph.node.count", _tagged);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<int?> _fault_CountAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
