//HintName: RerankerInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class RerankerInstrumented : IReranker
{
    private static readonly ActivitySource _activitySource = new("MyApp.Rerank");
    private static readonly Meter _meter = new("MyApp.Rerank");

    private readonly IReranker _inner;
    public RerankerInstrumented(IReranker inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<string> RerankAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.run");
        _activity?.SetTag("reranker.type", "CohereReranker");
        _activity?.SetTag("gen_ai.operation.name", "chat");
        _activity?.SetTag("vectorstore.hybrid", true);
        _activity?.SetTag("rerank.max", 42);
        _activity?.SetTag("graphrag.search.mode", (global::SearchMode)2);
        try
        {
            var _result = await _inner.RerankAsync(ct);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
