//HintName: IOrderService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrderServiceInstrumented : IOrderService
{
    private static readonly ActivitySource _activitySource = new("MyApp.Orders");
    private static readonly Meter _meter = new("MyApp.Orders");
    private static readonly Counter<long> _orders_created = _meter.CreateCounter<long>("orders.created");
    private static readonly Histogram<double> _order_create_ms = _meter.CreateHistogram<double>("order.create_ms");

    private readonly IOrderService _inner;
    public OrderServiceInstrumented(IOrderService inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<string> CreateOrderAsync(string orderId, global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners() && !_orders_created.Enabled && !_order_create_ms.Enabled)
            return _inner.CreateOrderAsync(orderId, ct);
        return _core_CreateOrderAsync_0(orderId, ct);
    }

    private async global::System.Threading.Tasks.ValueTask<string> _core_CreateOrderAsync_0(string orderId, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("order.create");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.CreateOrderAsync(orderId, ct);
            _orders_created.Add(1);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            _order_create_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }
}
