//HintName: IPooledService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PooledServiceInstrumented : IPooledService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Histogram<double> _pooled_list_ms = _meter.CreateHistogram<double>("pooled.list.ms");
    private static readonly Counter<long> _pooled_items = _meter.CreateCounter<long>("pooled.items");
    private static readonly Histogram<double> _pooled_run_ms = _meter.CreateHistogram<double>("pooled.run.ms");

    private readonly IPooledService _inner;
    public PooledServiceInstrumented(IPooledService inner) => _inner = inner;

    public async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> ListAsync()
    {
        using var _activity = _activitySource.StartActivity("pooled.list");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.ListAsync();
            _pooled_list_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            _pooled_list_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    public async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> CountAsync()
    {
        using var _activity = _activitySource.StartActivity("pooled.count");
        try
        {
            var _result = await _inner.CountAsync();
            var _tagged = _result;
            _activity?.SetTag("items.count", _tagged?.Count);
            if (_tagged?.Count is { } _read0)
                _pooled_items.Add(_read0);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    public async global::Pooled.PooledTask RunAsync()
    {
        using var _activity = _activitySource.StartActivity("pooled.run");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            await _inner.RunAsync();
            _pooled_run_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            _pooled_run_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }
}
