//HintName: ISharedService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

public sealed class SharedServiceInstrumented : ISharedService
{
    private static readonly ActivitySource _activitySource = new("MyApp.Shared");
    private static readonly Meter _meter = new("MyApp.Shared");

    private readonly ISharedService _inner;
    public SharedServiceInstrumented(ISharedService inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask RunAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.RunAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_RunAsync_0(_ex);
            }
        }
        return _core_RunAsync_0(ct);
    }

    private async global::System.Threading.Tasks.ValueTask _core_RunAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("shared.run");
        try
        {
            await _inner.RunAsync(ct);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask _fault_RunAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
    }
}
