//HintName: IReranker.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class RerankerInstrumented : IReranker
{
    private static readonly ActivitySource _activitySource = new("MyApp.Rerank");
    private static readonly Meter _meter = new("MyApp.Rerank");

    private readonly IReranker _inner;
    public RerankerInstrumented(IReranker inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::RerankOutcome> RerankAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.RerankAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_RerankAsync_0(_ex);
            }
        }
        return _core_RerankAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<global::RerankOutcome> _core_RerankAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.run");
        try
        {
            var _result = await _inner.RerankAsync(ct).ConfigureAwait(false);
            var _tagged = _result;
            _activity?.SetTag("rerank.candidate.count", _tagged?.Candidates);
            _activity?.SetTag("rerank.result.count", _tagged?.Kept);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::RerankOutcome> _fault_RerankAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<double> ScoreAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.ScoreAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_ScoreAsync_1(_ex);
            }
        }
        return _core_ScoreAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<double> _core_ScoreAsync_1(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.score");
        try
        {
            var _result = await _inner.ScoreAsync(ct).ConfigureAwait(false);
            _activity?.SetTag("rerank.score", _result);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<double> _fault_ScoreAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
