//HintName: IAwkward.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class AwkwardInstrumented : IAwkward
{
    private static readonly ActivitySource _activitySource = new("MyApp.Awkward");
    private static readonly Meter _meter = new("MyApp.Awkward");

    private readonly IAwkward _inner;
    public AwkwardInstrumented(IAwkward inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<string> RunAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.RunAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_RunAsync_0(_ex);
            }
        }
        return _core_RunAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<string> _core_RunAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("awkward.run");
        _activity?.SetTag("quote", "he said \"hi\"");
        _activity?.SetTag("path", "C:\\temp\\x");
        try
        {
            var _result = await _inner.RunAsync(ct).ConfigureAwait(false);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<string> _fault_RunAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
