//HintName: ReportServiceInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class ReportServiceInstrumented : IReportService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Counter<long> _reports_built = _meter.CreateCounter<long>("reports.built");

    private readonly IReportService _inner;
    public ReportServiceInstrumented(IReportService inner) => _inner = inner;

    public global::TaskReport Build()
    {
        try
        {
            var _result = _inner.Build();
            _reports_built.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }
}
