//HintName: IngestInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class IngestInstrumented : IIngest
{
    private static readonly ActivitySource _activitySource = new("MyApp.Ingest");
    private static readonly Meter _meter = new("MyApp.Ingest");

    private readonly IIngest _inner;
    public IngestInstrumented(IIngest inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task StoreAsync(global::DocumentMetadata metadata, global::System.Collections.Generic.IReadOnlyList<string> chunks, global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("ingest.store");
        var _tag_metadata = metadata;
        _activity?.SetTag("document.id", _tag_metadata?.DocumentId?.Value);
        var _tag_chunks = chunks;
        _activity?.SetTag("vectorstore.batch.size", _tag_chunks?.Count);
        try
        {
            await _inner.StoreAsync(metadata, chunks, ct);
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
