//HintName: IIngest.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class IngestInstrumented : IIngest
{
    private static readonly ActivitySource _activitySource = new("MyApp.Ingest");
    private static readonly Meter _meter = new("MyApp.Ingest");

    private readonly IIngest _inner;
    public IngestInstrumented(IIngest inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::Result<global::System.Collections.Generic.IReadOnlyList<global::Chunk>, global::RagError>> ChunkAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.ChunkAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_ChunkAsync_0(_ex);
            }
        }
        return _core_ChunkAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<global::Result<global::System.Collections.Generic.IReadOnlyList<global::Chunk>, global::RagError>> _core_ChunkAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("ingest.chunk");
        try
        {
            var _result = await _inner.ChunkAsync(ct).ConfigureAwait(false);
            var _tagged = _result;
            if (_tagged?.IsSuccess == true)
                _activity?.SetTag("chunk.count", _tagged?.Value?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::Result<global::System.Collections.Generic.IReadOnlyList<global::Chunk>, global::RagError>> _fault_ChunkAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
