//HintName: IPooledService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PooledServiceInstrumented : IPooledService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Histogram<double> _pooled_list_ms = _meter.CreateHistogram<double>("pooled.list.ms");
    private static readonly Counter<long> _pooled_items = _meter.CreateCounter<long>("pooled.items");
    private static readonly Histogram<double> _pooled_run_ms = _meter.CreateHistogram<double>("pooled.run.ms");

    private readonly IPooledService _inner;
    public PooledServiceInstrumented(IPooledService inner) => _inner = inner;

    public global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> ListAsync()
    {
        if (!_activitySource.HasListeners() && !_pooled_list_ms.Enabled)
        {
            try
            {
                return _inner.ListAsync();
            }
            catch (Exception _ex)
            {
                return _fault_ListAsync_0(_ex);
            }
        }
        return _core_ListAsync_0();
    }

    private async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> _core_ListAsync_0()
    {
        using var _activity = _activitySource.StartActivity("pooled.list");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.ListAsync();
            _pooled_list_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            if (_pooled_list_ms.Enabled)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("error.type", _ex.GetType().FullName);
                _pooled_list_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds, in _metricTags0);
            }
            throw;
        }
    }

    private static async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> _fault_ListAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> CountAsync()
    {
        if (!_activitySource.HasListeners() && !_pooled_items.Enabled)
        {
            try
            {
                return _inner.CountAsync();
            }
            catch (Exception _ex)
            {
                return _fault_CountAsync_1(_ex);
            }
        }
        return _core_CountAsync_1();
    }

    private async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> _core_CountAsync_1()
    {
        using var _activity = _activitySource.StartActivity("pooled.count");
        try
        {
            var _result = await _inner.CountAsync();
            var _tagged = _result;
            _activity?.SetTag("items.count", _tagged?.Count);
            if (_tagged?.Count is { } _read0)
                _pooled_items.Add(_read0);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::Pooled.PooledTask<global::System.Collections.Generic.List<int>> _fault_CountAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::Pooled.PooledTask RunAsync()
    {
        if (!_activitySource.HasListeners() && !_pooled_run_ms.Enabled)
        {
            try
            {
                return _inner.RunAsync();
            }
            catch (Exception _ex)
            {
                return _fault_RunAsync_2(_ex);
            }
        }
        return _core_RunAsync_2();
    }

    private async global::Pooled.PooledTask _core_RunAsync_2()
    {
        using var _activity = _activitySource.StartActivity("pooled.run");
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            await _inner.RunAsync();
            _pooled_run_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            if (_pooled_run_ms.Enabled)
            {
                var _metricTags0 = new TagList();
                _metricTags0.Add("error.type", _ex.GetType().FullName);
                _pooled_run_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds, in _metricTags0);
            }
            throw;
        }
    }

    private static async global::Pooled.PooledTask _fault_RunAsync_2(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
    }
}
