//HintName: IReranker.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class RerankerInstrumented : IReranker
{
    private static readonly ActivitySource _activitySource = new("MyApp.Rerank");
    private static readonly Meter _meter = new("MyApp.Rerank");

    private readonly IReranker _inner;
    public RerankerInstrumented(IReranker inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<string> RerankAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.RerankAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_RerankAsync_0(_ex);
            }
        }
        return _core_RerankAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<string> _core_RerankAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("rerank.run");
        _activity?.SetTag("reranker.type", "CohereReranker");
        _activity?.SetTag("gen_ai.operation.name", "chat");
        _activity?.SetTag("vectorstore.hybrid", true);
        _activity?.SetTag("rerank.max", 42);
        _activity?.SetTag("graphrag.search.mode", (global::SearchMode)2);
        try
        {
            var _result = await _inner.RerankAsync(ct).ConfigureAwait(false);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetTag("error.type", _ex.GetType().FullName);
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<string> _fault_RerankAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
