//HintName: IPlainService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PlainServiceInstrumented : IPlainService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Counter<long> _plain_calls = _meter.CreateCounter<long>("plain.calls");

    private readonly IPlainService _inner;
    public PlainServiceInstrumented(IPlainService inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<string> RunAsync(string arg, global::System.Threading.CancellationToken ct)
    {
        if (!_plain_calls.Enabled)
            return _inner.RunAsync(arg, ct);
        return _core_RunAsync_0(arg, ct);
    }

    private async global::System.Threading.Tasks.Task<string> _core_RunAsync_0(string arg, global::System.Threading.CancellationToken ct)
    {
        try
        {
            var _result = await _inner.RunAsync(arg, ct);
            _plain_calls.Add(1);
            return _result;
        }
        catch (Exception)
        {
            throw;
        }
    }
}
