//HintName: IPaths.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class PathsInstrumented : IPaths
{
    private static readonly ActivitySource _activitySource = new("MyApp.Paths");
    private static readonly Meter _meter = new("MyApp.Paths");

    private readonly IPaths _inner;
    public PathsInstrumented(IPaths inner) => _inner = inner;

    public global::System.Threading.Tasks.Task<global::Outer> DeepAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.DeepAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_DeepAsync_0(_ex);
            }
        }
        return _core_DeepAsync_0(ct);
    }

    private async global::System.Threading.Tasks.Task<global::Outer> _core_DeepAsync_0(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("paths.deep");
        try
        {
            var _result = await _inner.DeepAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("deep.count", _tagged?.Inner?.Items?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::Outer> _fault_DeepAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }

    public global::System.Threading.Tasks.Task<global::Outer> ValueAsync(global::System.Threading.CancellationToken ct)
    {
        if (!_activitySource.HasListeners())
        {
            try
            {
                return _inner.ValueAsync(ct);
            }
            catch (Exception _ex)
            {
                return _fault_ValueAsync_1(_ex);
            }
        }
        return _core_ValueAsync_1(ct);
    }

    private async global::System.Threading.Tasks.Task<global::Outer> _core_ValueAsync_1(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("paths.value");
        try
        {
            var _result = await _inner.ValueAsync(ct);
            var _tagged = _result;
            _activity?.SetTag("value.total", _tagged?.Total);
            _activity?.SetTag("value.width", _tagged?.Extent.Width);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.Task<global::Outer> _fault_ValueAsync_1(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
