//HintName: IOrderService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrderServiceInstrumented : IOrderService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Counter<long> _orders_created = _meter.CreateCounter<long>("orders.created");

    private readonly IOrderService _inner;
    public OrderServiceInstrumented(IOrderService inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask CreateOrderAsync(string orderId, global::System.Threading.CancellationToken ct)
    {
        if (!_orders_created.Enabled)
        {
            try
            {
                return _inner.CreateOrderAsync(orderId, ct);
            }
            catch (Exception _ex)
            {
                return _fault_CreateOrderAsync_0(_ex);
            }
        }
        return _core_CreateOrderAsync_0(orderId, ct);
    }

    private async global::System.Threading.Tasks.ValueTask _core_CreateOrderAsync_0(string orderId, global::System.Threading.CancellationToken ct)
    {
        try
        {
            await _inner.CreateOrderAsync(orderId, ct);
            _orders_created.Add(1);
        }
        catch (Exception)
        {
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask _fault_CreateOrderAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
    }
}
