//HintName: IOrderService.Instrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class OrderServiceInstrumented : IOrderService
{
    private static readonly ActivitySource _activitySource = new("MyApp");
    private static readonly Meter _meter = new("MyApp");
    private static readonly Histogram<double> _order_duration_ms = _meter.CreateHistogram<double>("order.duration_ms");

    private readonly IOrderService _inner;
    public OrderServiceInstrumented(IOrderService inner) => _inner = inner;

    public global::System.Threading.Tasks.ValueTask<string> GetOrderAsync(string orderId, global::System.Threading.CancellationToken ct)
    {
        if (!_order_duration_ms.Enabled)
        {
            try
            {
                return _inner.GetOrderAsync(orderId, ct);
            }
            catch (Exception _ex)
            {
                return _fault_GetOrderAsync_0(_ex);
            }
        }
        return _core_GetOrderAsync_0(orderId, ct);
    }

    private async global::System.Threading.Tasks.ValueTask<string> _core_GetOrderAsync_0(string orderId, global::System.Threading.CancellationToken ct)
    {
        var _sw = Stopwatch.GetTimestamp();
        try
        {
            var _result = await _inner.GetOrderAsync(orderId, ct);
            _order_duration_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            return _result;
        }
        catch (Exception)
        {
            _order_duration_ms.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);
            throw;
        }
    }

    private static async global::System.Threading.Tasks.ValueTask<string> _fault_GetOrderAsync_0(Exception _ex)
    {
        await global::System.Threading.Tasks.Task.CompletedTask;
        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);
        return default!;
    }
}
