//HintName: IngestInstrumented.g.cs
// <auto-generated />
#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

internal sealed class IngestInstrumented : IIngest
{
    private static readonly ActivitySource _activitySource = new("MyApp.Ingest");
    private static readonly Meter _meter = new("MyApp.Ingest");

    private readonly IIngest _inner;
    public IngestInstrumented(IIngest inner) => _inner = inner;

    public async global::System.Threading.Tasks.Task<global::Result<global::System.Collections.Generic.IReadOnlyList<global::Chunk>, global::RagError>> ChunkAsync(global::System.Threading.CancellationToken ct)
    {
        using var _activity = _activitySource.StartActivity("ingest.chunk");
        try
        {
            var _result = await _inner.ChunkAsync(ct);
            var _tagged = _result;
            if (_tagged?.IsSuccess == true)
                _activity?.SetTag("chunk.count", _tagged?.Value?.Count);
            return _result;
        }
        catch (Exception _ex)
        {
            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);
            throw;
        }
    }
}
