using System.Text;
using ZeroAlloc.Telemetry.Generator.Models;

namespace ZeroAlloc.Telemetry.Generator;

internal static class ProxyWriter
{
    public static string Write(InstrumentModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Diagnostics.Metrics;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var accessibility = model.PublicProxy ? "public" : "internal";
        sb.AppendLine($"{accessibility} sealed class {model.ProxyName} : {model.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly ActivitySource _activitySource = new(\"{model.ActivitySourceName}\");");
        sb.AppendLine($"    private static readonly Meter _meter = new(\"{model.ActivitySourceName}\");");

        WriteMetricFields(sb, model);

        sb.AppendLine();
        sb.AppendLine($"    private readonly {model.InterfaceName} _inner;");
        sb.AppendLine($"    public {model.ProxyName}({model.InterfaceName} inner) => _inner = inner;");

        foreach (var method in model.Methods)
            WriteMethod(sb, method);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteMetricFields(StringBuilder sb, InstrumentModel model)
    {
        var emittedMetrics = new HashSet<string>(StringComparer.Ordinal);
        foreach (var method in model.Methods)
        {
            if (method.CountMetric is not null && emittedMetrics.Add(method.CountMetric))
            {
                var fieldName = ToFieldName(method.CountMetric);
                sb.AppendLine($"    private static readonly Counter<long> _{fieldName} = _meter.CreateCounter<long>(\"{method.CountMetric}\");");
            }

            if (method.HistogramMetric is not null && emittedMetrics.Add(method.HistogramMetric))
            {
                var fieldName = ToFieldName(method.HistogramMetric);
                sb.AppendLine($"    private static readonly Histogram<double> _{fieldName} = _meter.CreateHistogram<double>(\"{method.HistogramMetric}\");");
            }
        }
    }

    private static void WriteMethod(StringBuilder sb, MethodModel method)
    {
        sb.AppendLine();

        var asyncKeyword = method.IsAsync ? "async " : string.Empty;
        var paramList    = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var argList      = string.Join(", ", method.Parameters.Select(p => p.Name));

        sb.AppendLine($"    public {asyncKeyword}{method.ReturnType} {method.Name}({paramList})");
        sb.AppendLine("    {");

        if (method.TraceName is not null)
        {
            sb.AppendLine($"        using var _activity = _activitySource.StartActivity(\"{method.TraceName}\");");

            // Set immediately after the span starts so the tags are present for its whole
            // lifetime. `_activity?.` short-circuits the whole call when nothing sampled the
            // span, so an unsampled call neither evaluates nor boxes the argument.
            foreach (var p in method.Parameters)
            {
                if (p.TagName is not null)
                    sb.AppendLine($"        _activity?.SetTag(\"{p.TagName}\", {p.Name});");
            }
        }

        if (method.HistogramMetric is not null)
            sb.AppendLine("        var _sw = Stopwatch.GetTimestamp();");

        var needsTry = method.TraceName is not null
                    || method.HistogramMetric is not null
                    || method.CountMetric is not null;

        if (needsTry)
            WriteInstrumentedBody(sb, method, argList);
        else
            WritePassthroughBody(sb, method, argList);

        sb.AppendLine("    }");
    }

    private static void WriteInstrumentedBody(StringBuilder sb, MethodModel method, string argList)
    {
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        var awaitKeyword = method.IsAsync ? "await " : string.Empty;
        var callExpr     = $"{awaitKeyword}_inner.{method.Name}({argList})";

        if (method.ReturnsVoid)
            sb.AppendLine($"            {callExpr};");
        else
            sb.AppendLine($"            var _result = {callExpr};");

        // Result tags come first so they are recorded even if a metric line below were to change.
        // Only emitted with a span to carry them and a value to read; ZTEL004/ZTEL005 warn otherwise.
        if (method.TraceName is not null && !method.ReturnsVoid && method.ResultTags.Count > 0)
            WriteResultTags(sb, method);

        if (method.CountMetric is not null)
        {
            var fieldName = ToFieldName(method.CountMetric);
            sb.AppendLine($"            _{fieldName}.Add(1);");
        }

        if (method.HistogramMetric is not null)
        {
            var fieldName = ToFieldName(method.HistogramMetric);
            sb.AppendLine($"            _{fieldName}.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);");
        }

        if (!method.ReturnsVoid)
            sb.AppendLine("            return _result;");

        sb.AppendLine("        }");
        WriteCatchBlock(sb, method);
    }

    /// <summary>
    /// Emits the result-derived tags.
    /// </summary>
    /// <remarks>
    /// Member access goes through a copy of the result rather than the result itself. Roslyn
    /// treats <c>_result?.Member</c> as a null test on <c>_result</c>, which leaves it in a
    /// maybe-null state — and the following <c>return _result;</c> then raises CS8603 in any
    /// consumer with nullable warnings enabled. Testing the copy keeps the returned value's
    /// null-state intact while still guaranteeing instrumentation cannot throw on a null result.
    /// </remarks>
    private static void WriteResultTags(StringBuilder sb, MethodModel method)
    {
        var needsCopy = method.ResultCanBeNull
                     && method.ResultTags.Any(t => !string.IsNullOrEmpty(t.Member));

        if (needsCopy)
            sb.AppendLine("            var _tagged = _result;");

        foreach (var tag in method.ResultTags)
        {
            string access;
            if (string.IsNullOrEmpty(tag.Member))
            {
                // No member access, so no null test and no effect on _result's null-state.
                access = "_result";
            }
            else if (method.ResultCanBeNull)
            {
                access = $"_tagged?.{tag.Member}";
            }
            else
            {
                // `?.` against a non-nullable value type does not compile, and a value type
                // cannot be null, so plain access is both required and safe.
                access = $"_result.{tag.Member}";
            }

            sb.AppendLine($"            _activity?.SetTag(\"{tag.TagName}\", {access});");
        }
    }

    private static void WriteCatchBlock(StringBuilder sb, MethodModel method)
    {
        sb.AppendLine("        catch (Exception _ex)");
        sb.AppendLine("        {");

        if (method.TraceName is not null)
            sb.AppendLine("            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);");

        if (method.HistogramMetric is not null)
        {
            var fieldName = ToFieldName(method.HistogramMetric);
            sb.AppendLine($"            _{fieldName}.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);");
        }

        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
    }

    private static void WritePassthroughBody(StringBuilder sb, MethodModel method, string argList)
    {
        var awaitKeyword  = method.IsAsync ? "await " : string.Empty;
        var callExpr      = $"{awaitKeyword}_inner.{method.Name}({argList})";
        var returnKeyword = method.ReturnsVoid ? string.Empty : "return ";
        sb.AppendLine($"        {returnKeyword}{callExpr};");
    }

    private static string ToFieldName(string metric) =>
        metric.Replace('.', '_').Replace('-', '_');
}
