using System.Globalization;
using System.Text;
using ZeroAlloc.Telemetry.Generator.Models;

namespace ZeroAlloc.Telemetry.Generator;

internal static class ProxyWriter
{
    public static string Write(InstrumentModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        // The <auto-generated> header exempts a file from analyzer diagnostics by convention,
        // but ErrorProne.NET analyses generated files anyway — so EPC12 reaches consumers.
        // It fires on the catch block below, which reads _ex.Message for the span status and
        // then rethrows with a bare `throw;`. Nothing is swallowed, so the diagnostic is a
        // false positive; suppressing it here spares every adopter their own <NoWarn>.
        // File-scoped, so it cannot leak into consumer-authored code.
        sb.AppendLine("#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Diagnostics.Metrics;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // A nested interface's proxy is emitted next to it, inside partial declarations of its
        // containing types, so it can name the interface as the interface's siblings do.
        foreach (var containing in model.ContainingTypes)
        {
            sb.AppendLine(containing);
            sb.AppendLine("{");
        }

        var accessibility = model.PublicProxy ? "public" : "internal";
        sb.AppendLine($"{accessibility} sealed class {model.ProxyName}{model.TypeParameters} : {model.InterfaceName}");
        // The proxy is a new type, so a generic one repeats the interface's constraints.
        foreach (var clause in model.ConstraintClauses)
            sb.AppendLine($"    {clause}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly ActivitySource _activitySource = new({Literal(model.ActivitySourceName)});");
        sb.AppendLine($"    private static readonly Meter _meter = new({Literal(model.ActivitySourceName)});");

        var fields = MetricFieldTable.Build(model);
        WriteMetricFields(sb, fields);

        sb.AppendLine();
        WriteFieldsAndConstructor(sb, model);

        for (var i = 0; i < model.Methods.Count; i++)
        {
            WriteMethod(sb, model.Methods[i], i, fields);
            if (HasStartTags(model.Methods[i]))
                WriteStartTagsMethod(sb, model.Methods[i], i);
        }

        if (model.Methods.Any(static m => m.ResultMetrics.Any(static r => r.Each is EachKind.Span or EachKind.Memory)))
            WriteRecordEachHelpers(sb);

        sb.AppendLine("}");
        for (var i = 0; i < model.ContainingTypes.Count; i++)
            sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits the wrapped instance field, any resolved span-name fields, and the constructor.
    /// </summary>
    /// <remarks>
    /// Span names containing <c>{type}</c> vary by implementation, so they cannot be literals at
    /// the call site. They are resolved once in the constructor instead: the wrapped instance
    /// cannot change for the lifetime of the proxy, so the name is stable, and composing it here
    /// keeps the per-call path free of string concatenation.
    /// </remarks>
    private static void WriteFieldsAndConstructor(StringBuilder sb, InstrumentModel model)
    {
        sb.AppendLine($"    private readonly {model.InterfaceName} _inner;");

        var templated = model.Methods
            .Select((m, i) => (Method: m, Index: i))
            .Where(x => x.Method.TraceNameExpression is not null)
            .ToList();

        foreach (var (method, index) in templated)
            sb.AppendLine($"    private readonly string {SpanNameField(method, index)};");

        if (templated.Count == 0)
        {
            sb.AppendLine($"    public {model.ProxyName}({model.InterfaceName} inner) => _inner = inner;");
            return;
        }

        sb.AppendLine($"    public {model.ProxyName}({model.InterfaceName} inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        sb.AppendLine("        // Composed once per wrapped instance. Doing it per call would allocate a");
        sb.AppendLine("        // string on every invocation of an instrumented method.");
        sb.AppendLine("        var _implName = inner.GetType().Name;");
        foreach (var (method, index) in templated)
            sb.AppendLine($"        {SpanNameField(method, index)} = {method.TraceNameExpression};");
        sb.AppendLine("    }");
    }

    private static void WriteMetricFields(StringBuilder sb, MetricFieldTable fields)
    {
        foreach (var field in fields.Fields)
        {
            var (type, factory) = field.Kind == MetricKind.Counter
                ? ("Counter<long>", "CreateCounter<long>")
                : ("Histogram<double>", "CreateHistogram<double>");

            sb.AppendLine($"    private static readonly {type} {field.FieldName} = _meter.{factory}({FactoryArguments(field)});");
        }
    }

    /// <summary>
    /// Records every element of a span in a histogram. A span cannot be iterated in the proxy's
    /// async method on every language version the proxy compiles under, so it is handed here.
    /// </summary>
    private static void WriteRecordEachHelpers(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    private static void _recordEach(Histogram<double> histogram, ReadOnlySpan<double> values)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (ref readonly var value in values)");
        sb.AppendLine("            histogram.Record(value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void _recordEach(Histogram<double> histogram, ReadOnlySpan<double> values, in TagList tags)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (ref readonly var value in values)");
        sb.AppendLine("            histogram.Record(value, in tags);");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Arguments to <c>CreateCounter</c>/<c>CreateHistogram</c>. Unit and description are named
    /// and only passed when set, so an instrument without them emits the same call as before.
    /// Bucket boundaries go through the overload that takes advice, which names every argument.
    /// </summary>
    private static string FactoryArguments(MetricFieldTable.Field field)
    {
        if (field.Buckets.Count > 0)
        {
            return Literal(field.Metric)
                + ", unit: " + (field.Unit is null ? "null" : Literal(field.Unit))
                + ", description: " + (field.Description is null ? "null" : Literal(field.Description))
                + ", tags: null"
                + ", advice: new InstrumentAdvice<double> { HistogramBucketBoundaries = new double[] { "
                + string.Join(", ", field.Buckets) + " } }";
        }

        var args = Literal(field.Metric);
        if (field.Unit is not null)
            args += ", unit: " + Literal(field.Unit);
        if (field.Description is not null)
            args += ", description: " + Literal(field.Description);

        return args;
    }

    /// <summary>
    /// Field holding a resolved <c>{type}</c> span name. Indexed as well as named, because
    /// overloads share a method name and would otherwise collide on one field.
    /// </summary>
    private static string SpanNameField(MethodModel method, int index) =>
        $"_spanName_{method.Name}_{index}";

    private static void WriteMethod(StringBuilder sb, MethodModel method, int index, MetricFieldTable fields)
    {
        sb.AppendLine();

        var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {Id(p.Name)}"));
        var argList   = string.Join(", ", method.Parameters.Select(p => Id(p.Name)));

        var instrumented = method.TraceName is not null
                        || method.Histogram is not null
                        || method.Count is not null
                        || method.ResultMetrics.Count > 0;

        if (!method.IsAsync)
        {
            WriteSignature(sb, method, "public ", Id(method.Name), paramList);
            sb.AppendLine("    {");
            if (instrumented)
                WriteInstrumentedPrologueAndBody(sb, method, index, argList, fields);
            else
                WritePassthroughBody(sb, method, argList);
            sb.AppendLine("    }");
            return;
        }

        // An awaitable method is never async itself. Awaiting in the public method would allocate
        // its state machine whenever the inner call completes asynchronously, even with nothing
        // listening, so the inner task is returned as is unless something would be recorded.
        var inner = $"_inner.{Id(method.Name)}{method.TypeParameters}({argList})";
        var fault = FaultMethodName(method, index);
        WriteSignature(sb, method, "public ", Id(method.Name), paramList);
        sb.AppendLine("    {");
        if (instrumented)
        {
            sb.AppendLine($"        if ({QuietCondition(method, fields)})");
            sb.AppendLine("        {");
            WriteForwardOrFault(sb, "            ", inner, fault + method.TypeParameters);
            sb.AppendLine("        }");
            sb.AppendLine($"        return {CoreMethodName(method, index)}{method.TypeParameters}({argList});");
        }
        else
        {
            WriteForwardOrFault(sb, "        ", inner, fault + method.TypeParameters);
        }
        sb.AppendLine("    }");

        if (instrumented)
        {
            sb.AppendLine();
            WriteSignature(sb, method, "private async ", CoreMethodName(method, index), paramList);
            sb.AppendLine("    {");
            WriteInstrumentedPrologueAndBody(sb, method, index, argList, fields);
            sb.AppendLine("    }");
        }

        WriteFaultMethod(sb, method, fault);
    }

    /// <summary>
    /// Returns the inner call's awaitable. An exception the inner method throws before returning
    /// one is handed back inside a faulted awaitable instead, so a caller sees it on the await,
    /// exactly as it would from the async core when something is listening.
    /// </summary>
    private static void WriteForwardOrFault(StringBuilder sb, string indent, string innerCall, string fault)
    {
        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    return {innerCall};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}catch (Exception _ex)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    return {fault}(_ex);");
        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    /// An async method that rethrows the exception it is given, so the method builder turns it
    /// into the awaitable an async method would return: faulted, or canceled for an
    /// <see cref="OperationCanceledException"/> with the exception kept. It runs only on the
    /// exception path, so the success path stays free of allocation, and it works for every
    /// awaitable the proxy supports, including task-like types with their own builder.
    /// </summary>
    private static void WriteFaultMethod(StringBuilder sb, MethodModel method, string name)
    {
        sb.AppendLine();
        WriteSignature(sb, method, "private static async ", name, "Exception _ex");
        sb.AppendLine("    {");
        sb.AppendLine("        await global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine("        global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(_ex);");
        if (!method.ReturnsVoid)
            sb.AppendLine("        return default!;");
        sb.AppendLine("    }");
    }

    /// <summary>The fault method of an awaitable method; see <see cref="WriteFaultMethod"/>.</summary>
    private static string FaultMethodName(MethodModel method, int index) =>
        $"_fault_{method.Name}_{index.ToString(CultureInfo.InvariantCulture)}";

    /// <summary>
    /// The method's declaration line and, for a generic method, its constraint clauses: an
    /// implicit implementation of a generic method has to repeat them, and so does the core
    /// method it calls, whose type parameters must satisfy the inner call's.
    /// </summary>
    private static void WriteSignature(StringBuilder sb, MethodModel method, string modifiers, string name, string paramList)
    {
        sb.AppendLine($"    {modifiers}{method.ReturnType} {name}{method.TypeParameters}({paramList})");
        foreach (var clause in method.ConstraintClauses)
            sb.AppendLine($"        {clause}");
    }

    /// <summary>
    /// The span, the stopwatch and the try block that records the method's instruments.
    /// </summary>
    private static void WriteInstrumentedPrologueAndBody(
        StringBuilder sb, MethodModel method, int index, string argList, MetricFieldTable fields)
    {
        if (method.TraceName is not null)
            WriteSpanStartAndTags(sb, method, index);

        if (method.Histogram is not null)
            sb.AppendLine("        var _sw = Stopwatch.GetTimestamp();");

        WriteInstrumentedBody(sb, method, argList, fields);
    }

    /// <summary>
    /// The async method holding an awaitable method's instrumentation. Indexed as well as named,
    /// so overloads do not collide, and prefixed so it cannot clash with an interface member.
    /// </summary>
    private static string CoreMethodName(MethodModel method, int index) =>
        $"_core_{method.Name}_{index.ToString(CultureInfo.InvariantCulture)}";

    /// <summary>
    /// True when nothing would observe the call: the source has no listener, for a traced method,
    /// and none of the method's instruments is enabled. Each check is a field read, so the fast
    /// path allocates nothing and costs a few branches.
    /// </summary>
    private static string QuietCondition(MethodModel method, MetricFieldTable fields)
    {
        var checks = new List<string>();
        if (method.TraceName is not null)
            checks.Add("!_activitySource.HasListeners()");

        if (method.Count is { } count)
            checks.Add($"!{fields.FieldFor(count)}.Enabled");

        if (method.Histogram is { } histogram)
            checks.Add($"!{fields.FieldFor(histogram)}.Enabled");

        foreach (var metric in method.ResultMetrics)
            checks.Add($"!{fields.FieldFor(metric)}.Enabled");

        return string.Join(" && ", checks);
    }

    /// <summary>
    /// Starts the span and sets the tags that are known before the wrapped call runs.
    /// </summary>
    private static void WriteSpanStartAndTags(StringBuilder sb, MethodModel method, int index)
    {
        // A templated name was resolved against the wrapped instance in the constructor; a
        // constant one is emitted inline, so the common case stays a plain string literal.
        var spanName = method.TraceNameExpression is not null
            ? SpanNameField(method, index)
            : Literal(method.TraceName!);
        var trace = method.Trace;
        var startTags = HasStartTags(method);

        if (startTags)
        {
            // The tags go to StartActivity, so a sampler sees them. They are only collected when
            // something listens; StartActivity returns null without a listener anyway.
            sb.AppendLine("        using var _activity = _activitySource.HasListeners()");
            sb.AppendLine($"            ? _activitySource.StartActivity({spanName}, {trace!.Kind ?? "ActivityKind.Internal"}, default(ActivityContext), {StartTagsMethodName(method, index)}{method.TypeParameters}({ArgList(method)}))");
            sb.AppendLine("            : null;");
        }
        else if (trace?.Kind is { } kind)
        {
            sb.AppendLine($"        using var _activity = _activitySource.StartActivity({spanName}, {kind});");
        }
        else
        {
            sb.AppendLine($"        using var _activity = _activitySource.StartActivity({spanName});");
        }

        if (trace?.DisplayName is { } displayName)
        {
            // Composed only for a sampled span, so an unsampled call builds no string.
            sb.AppendLine("        if (_activity is not null)");
            sb.AppendLine("        {");
            foreach (var copy in trace.DisplayNameCopies)
                sb.AppendLine($"            {copy}");
            sb.AppendLine($"            _activity.DisplayName = {displayName};");
            sb.AppendLine("        }");
        }

        if (!startTags)
            WriteStartedSpanTags(sb, method);
    }

    /// <summary>
    /// Sets the constant and parameter tags on the started span. `_activity?.` short-circuits the
    /// whole call when nothing sampled the span, so an unsampled call neither evaluates nor boxes
    /// the argument.
    /// </summary>
    private static void WriteStartedSpanTags(StringBuilder sb, MethodModel method)
    {
        // Constants first: they identify which implementation is running, so they are the
        // most useful thing present if a sampler inspects tags at ActivityStarted.
        foreach (var constant in method.ConstantTags)
            sb.AppendLine($"        _activity?.SetTag({Literal(constant.TagName)}, {constant.Literal});");

        foreach (var p in method.Parameters)
        {
            if (p.TagName is null)
                continue;

            // Read from a copy when the access null-tests the argument: Roslyn would
            // otherwise treat the argument as maybe-null for the rest of the method, and it
            // is forwarded to the inner call — CS8604 in any consumer with nullable warnings.
            var source = Id(p.Name);
            if (p.TagNeedsCopy)
            {
                source = $"_tag_{p.Name}";
                sb.AppendLine($"        var {source} = {Id(p.Name)};");
            }

            var access = p.TagAccessSuffix is { } suffix
                ? source + suffix
                : source;

            sb.AppendLine($"        _activity?.SetTag({Literal(p.TagName)}, {access});");
        }
    }

    /// <summary>Whether the method passes tags to <c>StartActivity</c>: asked for, and there are some.</summary>
    private static bool HasStartTags(MethodModel method) =>
        method.Trace is { TagsAtStart: true }
        && (method.ConstantTags.Count > 0 || method.Parameters.Any(static p => p.TagName is not null));

    private static string StartTagsMethodName(MethodModel method, int index) =>
        $"_startTags_{method.Name}_{index.ToString(CultureInfo.InvariantCulture)}";

    private static string ArgList(MethodModel method) =>
        string.Join(", ", method.Parameters.Select(p => Id(p.Name)));

    /// <summary>
    /// Collects the tags passed to <c>StartActivity</c>. A method of its own, so reading an
    /// argument through a null-conditional does not change its null-state where it is forwarded.
    /// A null value adds no tag, as <c>SetTag</c> adds none for a null.
    /// </summary>
    private static void WriteStartTagsMethod(StringBuilder sb, MethodModel method, int index)
    {
        sb.AppendLine();
        var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {Id(p.Name)}"));
        sb.AppendLine($"    private static TagList {StartTagsMethodName(method, index)}{method.TypeParameters}({paramList})");
        foreach (var clause in method.ConstraintClauses)
            sb.AppendLine($"        {clause}");
        sb.AppendLine("    {");
        sb.AppendLine("        var _startTags = new TagList();");

        foreach (var constant in method.ConstantTags)
        {
            if (!string.Equals(constant.Literal, "null", StringComparison.Ordinal))
                sb.AppendLine($"        _startTags.Add({Literal(constant.TagName)}, {constant.Literal});");
        }

        var n = 0;
        foreach (var p in method.Parameters)
        {
            if (p.TagName is null)
                continue;

            var access = Id(p.Name) + (p.TagAccessSuffix ?? string.Empty);
            if (p.TagCanBeNull)
            {
                var local = "_startTag" + (n++).ToString(CultureInfo.InvariantCulture);
                sb.AppendLine($"        if ({access} is {{ }} {local})");
                sb.AppendLine($"            _startTags.Add({Literal(p.TagName)}, {local});");
            }
            else
            {
                sb.AppendLine($"        _startTags.Add({Literal(p.TagName)}, {access});");
            }
        }

        sb.AppendLine("        return _startTags;");
        sb.AppendLine("    }");
    }

    private static void WriteInstrumentedBody(StringBuilder sb, MethodModel method, string argList, MetricFieldTable fields)
    {
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        var awaitKeyword = method.IsAsync ? "await " : string.Empty;
        var callExpr     = $"{awaitKeyword}_inner.{Id(method.Name)}{method.TypeParameters}({argList})";

        if (method.ReturnsVoid)
            sb.AppendLine($"            {callExpr};");
        else
            sb.AppendLine($"            var _result = {callExpr};");

        // Tags and result-driven instruments read the result, so they come first and share one
        // null-state copy. [Count] and [Histogram] follow, guarded when they have a When. Each
        // tagged measurement numbers its tag list, so every local on the method is distinct.
        var tagLists = 0;
        if (!method.ReturnsVoid)
            WriteResultReads(sb, method, fields, ref tagLists);

        var root = method.ResultCanBeNull ? "_tagged" : "_result";

        if (method.Count is { } count)
        {
            WriteMeasurement(
                sb, method, count, fields, Guard(root, count.GuardExpression), "1", root, ref tagLists);
        }

        if (method.Histogram is { } histogram)
        {
            WriteMeasurement(
                sb, method, histogram, fields, Guard(root, histogram.GuardExpression),
                Elapsed(histogram), root, ref tagLists);
        }

        if (!method.ReturnsVoid)
            sb.AppendLine("            return _result;");

        sb.AppendLine("        }");
        WriteCatchBlock(sb, method, fields, ref tagLists);
    }

    /// <summary>
    /// Emits everything that reads the result: the result-derived tags, when there is a span to
    /// carry them, then the result-driven instruments in attribute order.
    /// </summary>
    /// <remarks>
    /// Member access goes through a copy of the result rather than the result itself. Roslyn
    /// treats <c>_result?.Member</c> as a null test on <c>_result</c>, which leaves it in a
    /// maybe-null state — and the following <c>return _result;</c> then raises CS8603 in any
    /// consumer with nullable warnings enabled. Testing the copy keeps the returned value's
    /// null-state intact while still guaranteeing instrumentation cannot throw on a null result.
    /// </remarks>
    private static void WriteResultReads(StringBuilder sb, MethodModel method, MetricFieldTable fields, ref int tagLists)
    {
        // Tags need a span to carry them; ZTEL004 reports a result tag without one.
        var tags = method.TraceName is not null
            ? method.ResultTags
            : EquatableArray<ResultTagModel>.Empty;

        // Every read that null-tests the result goes through the copy: a member access, a guard,
        // or a metric value, which is always read through the root. A guarded tag that records
        // the whole result still null-tests _result in its guard, so it needs the copy too.
        var needsCopy = method.ResultCanBeNull
            && (method.Trace?.ErrorGuard is not null || NeedsResultCopy(method, tags));

        if (needsCopy)
            sb.AppendLine("            var _tagged = _result;");

        var root = method.ResultCanBeNull ? "_tagged" : "_result";

        foreach (var tag in tags)
            WriteResultTag(sb, tag, root);

        // The status after the tags, so a span marked failed still carries what the result said.
        if (method.Trace?.ErrorGuard is { } errorGuard)
        {
            var description = method.Trace.ErrorDescription is { } d ? ", " + root + d : string.Empty;
            sb.AppendLine($"            if (_activity is not null && {root}{errorGuard})");
            sb.AppendLine($"                _activity.SetStatus(ActivityStatusCode.Error{description});");
        }

        for (var i = 0; i < method.ResultMetrics.Count; i++)
            WriteResultMetric(sb, method, method.ResultMetrics[i], i, root, fields, ref tagLists);
    }

    /// <summary>Whether a tag, metric or guard reads the result through a null test.</summary>
    private static bool NeedsResultCopy(MethodModel method, EquatableArray<ResultTagModel> tags) =>
        tags.Any(t => !string.IsNullOrEmpty(t.Member) || t.GuardExpression is not null)
        || method.ResultMetrics.Count > 0
        || method.MetricTags.Any(static t => t.ReadsResult)
        || method.Count?.GuardExpression is not null
        || method.Histogram?.GuardExpression is not null;

    private static void WriteResultTag(StringBuilder sb, ResultTagModel tag, string root)
    {
        // No member records the result itself: no member access, so no null test and no
        // effect on _result's null-state. Otherwise the generator resolved the path, choosing
        // the operator for every segment, and reported ZTEL007 instead where it could not.
        var access = string.IsNullOrEmpty(tag.Member) ? "_result" : root + tag.AccessSuffix;

        if (tag.GuardExpression is { } guard)
        {
            // The guard has to prevent the member being read at all, which a null-conditional
            // cannot: `?.` protects against a null result, not against a result whose value is
            // unset. Reading Value on a failed Result is meaningless at best and throws at worst.
            sb.AppendLine($"            if ({root}{guard})");
            sb.AppendLine($"                _activity?.SetTag({Literal(tag.TagName)}, {access});");
        }
        else
        {
            sb.AppendLine($"            _activity?.SetTag({Literal(tag.TagName)}, {access});");
        }
    }

    /// <summary>
    /// Emits one <c>[CountFromResult]</c> or <c>[HistogramFromResult]</c>. <paramref name="index"/>
    /// numbers its pattern local, so each read on a method binds a distinct name.
    /// </summary>
    private static void WriteResultMetric(
        StringBuilder sb, MethodModel method, MetricModel metric, int index, string root, MetricFieldTable fields, ref int tagLists)
    {
        var access = root + metric.ValueAccess;
        var guard = metric.GuardExpression is { } g ? root + g : null;

        // A value that can be null is bound by a pattern: a null is skipped, and the local is
        // non-nullable, so it converts to long or double without a cast. The guard comes first
        // and short-circuits, so the member is not read at all when the guard is false.
        string? condition;
        string value;
        if (metric.ValueCanBeNull)
        {
            var local = "_read" + index.ToString(CultureInfo.InvariantCulture);
            var test = $"{access} is {{ }} {local}";
            condition = guard is null ? test : $"{guard} && {test}";
            value = local;
        }
        else
        {
            condition = guard;
            value = access;
        }

        if (metric.ValueIsDecimal)
            value = "(double)" + value;

        WriteMeasurement(sb, method, metric, fields, condition, value, root, ref tagLists, index);
    }

    /// <summary>The guard appended to the result root, or null when there is none.</summary>
    private static string? Guard(string root, string? guardExpression) =>
        guardExpression is null ? null : root + guardExpression;

    /// <summary>
    /// Emits one <c>Add</c> or <c>Record</c> of <paramref name="value"/>, under
    /// <paramref name="condition"/> when there is one, with the metric tags that apply to the metric.
    /// </summary>
    /// <remarks>
    /// <para>
    /// With tags, the measurement is behind the instrument's <c>Enabled</c>, checked first. With
    /// no listener the call is skipped before the tag list is built, a member is read or a value
    /// is boxed, so the no-listener path stays allocation-free. Nothing that would have been
    /// recorded is lost: a disabled instrument drops every measurement anyway. A per-element
    /// histogram is always behind <c>Enabled</c>, so its elements are not iterated for nothing.
    /// </para>
    /// <para>
    /// A null <paramref name="root"/> means there is no result, as on the throw path: only the
    /// tags that do not read the result are added. Without tags the emitted code is exactly what
    /// it was before tags existed.
    /// </para>
    /// </remarks>
    private static void WriteMeasurement(
        StringBuilder sb,
        MethodModel method,
        MetricModel metric,
        MetricFieldTable fields,
        string? condition,
        string value,
        string? root,
        ref int tagLists,
        int index = 0)
    {
        var field = fields.FieldFor(metric);

        List<MetricTagModel>? tags = null;
        foreach (var tag in method.MetricTags)
        {
            if (tag.AppliesTo(metric) && (root is not null || !tag.ReadsResult))
                (tags ??= new List<MetricTagModel>()).Add(tag);
        }

        var enabled = field + ".Enabled";
        if (tags is null)
        {
            if (metric.Each != EachKind.None)
                condition = condition is null ? enabled : enabled + " && " + condition;

            if (condition is null)
            {
                WriteRecord(sb, "            ", metric, field, value, null, index);
            }
            else
            {
                sb.AppendLine($"            if ({condition})");
                WriteRecord(sb, "                ", metric, field, value, null, index);
            }

            return;
        }

        var listIndex = (tagLists++).ToString(CultureInfo.InvariantCulture);
        var list = "_metricTags" + listIndex;

        sb.AppendLine($"            if ({(condition is null ? enabled : enabled + " && " + condition)})");
        sb.AppendLine("            {");
        sb.AppendLine($"                var {list} = new TagList();");

        for (var k = 0; k < tags.Count; k++)
            WriteMetricTag(sb, tags[k], list, $"_metricTag{listIndex}_{k.ToString(CultureInfo.InvariantCulture)}", root);

        WriteRecord(sb, "                ", metric, field, value, list, index);
        sb.AppendLine("            }");
    }

    /// <summary>
    /// The <c>Add</c> or <c>Record</c> itself: one call, or one per element for a per-element
    /// histogram. <paramref name="list"/> is the tag list, or null for none.
    /// </summary>
    private static void WriteRecord(
        StringBuilder sb, string indent, MetricModel metric, string field, string value, string? list, int index)
    {
        var operation = metric.Kind == MetricKind.Counter ? "Add" : "Record";
        var tagArgument = list is null ? string.Empty : ", in " + list;

        switch (metric.Each)
        {
            case EachKind.Span:
                sb.AppendLine($"{indent}_recordEach({field}, {value}{tagArgument});");
                return;

            case EachKind.Memory:
                sb.AppendLine($"{indent}_recordEach({field}, {value}.Span{tagArgument});");
                return;

            case EachKind.Enumerable:
                var element = "_each" + index.ToString(CultureInfo.InvariantCulture);
                sb.AppendLine($"{indent}foreach (var {element} in {value})");
                if (metric.ElementCanBeNull)
                {
                    var bound = "_eachValue" + index.ToString(CultureInfo.InvariantCulture);
                    sb.AppendLine($"{indent}    if ({element} is {{ }} {bound})");
                    sb.AppendLine($"{indent}        {field}.{operation}({Cast(metric, bound)}{tagArgument});");
                }
                else
                {
                    sb.AppendLine($"{indent}    {field}.{operation}({Cast(metric, element)}{tagArgument});");
                }

                return;

            default:
                sb.AppendLine($"{indent}{field}.{operation}({value}{tagArgument});");
                return;
        }
    }

    private static string Cast(MetricModel metric, string element) =>
        metric.ElementIsDecimal ? "(double)" + element : element;

    /// <summary>
    /// Adds one tag to <paramref name="list"/>. The guard comes first and short-circuits, so the
    /// member is not read when it is false. A null value is bound away by the pattern and adds no
    /// tag, as <c>Activity.SetTag</c> adds none for a null.
    /// </summary>
    private static void WriteMetricTag(StringBuilder sb, MetricTagModel tag, string list, string local, string? root)
    {
        // A constant or a parameter is its own root; only a result tag reads the result.
        var access = (tag.Root ?? root) + tag.Access;
        var guard = Guard(root ?? string.Empty, tag.GuardExpression);

        string? condition;
        string value;
        if (tag.ValueCanBeNull)
        {
            var test = $"{access} is {{ }} {local}";
            condition = guard is null ? test : $"{guard} && {test}";
            value = local;
        }
        else
        {
            condition = guard;
            value = access;
        }

        var add = $"{list}.Add({Literal(tag.TagName)}, {value});";
        if (condition is null)
        {
            sb.AppendLine($"                {add}");
        }
        else
        {
            sb.AppendLine($"                if ({condition})");
            sb.AppendLine($"                    {add}");
        }
    }

    /// <summary>The elapsed time of the call, in the histogram's unit.</summary>
    private static string Elapsed(MetricModel histogram) =>
        "Stopwatch.GetElapsedTime(_sw)." + histogram.ElapsedMember;

    private static void WriteCatchBlock(StringBuilder sb, MethodModel method, MetricFieldTable fields, ref int tagLists)
    {
        // Only the span reads the exception. Declaring the variable otherwise raises CS0168 in
        // the generated file, and that fails every consumer building with TreatWarningsAsErrors.
        sb.AppendLine(method.TraceName is not null
            ? "        catch (Exception _ex)"
            : "        catch (Exception)");
        sb.AppendLine("        {");

        if (method.TraceName is not null)
            sb.AppendLine("            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);");

        // A guarded histogram records only when its guard holds, and a throw leaves no result to
        // evaluate it against. An unguarded one records on both paths, as it always has.
        if (method.Histogram is { GuardExpression: null } histogram)
        {
            WriteMeasurement(
                sb, method, histogram, fields, null, Elapsed(histogram), root: null, ref tagLists);
        }

        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
    }

    /// <summary>Forwards a synchronous call that has no instruments.</summary>
    private static void WritePassthroughBody(StringBuilder sb, MethodModel method, string argList)
    {
        var callExpr      = $"_inner.{Id(method.Name)}{method.TypeParameters}({argList})";
        var returnKeyword = method.ReturnsVoid ? string.Empty : "return ";
        sb.AppendLine($"        {returnKeyword}{callExpr};");
    }

    /// <summary>A method or parameter name as an identifier: a keyword gets the verbatim <c>@</c> prefix.</summary>
    private static string Id(string name) => TypeDeclarations.Identifier(name);

    /// <summary>
    /// A name as a C# string literal, escaped the way the language writes it. A quote or a
    /// backslash in a metric, span or tag name would otherwise emit code that does not compile.
    /// </summary>
    private static string Literal(string value) =>
        Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
}
