using System.Globalization;
using System.Text;
using ZeroAlloc.Telemetry.Generator.Models;

namespace ZeroAlloc.Telemetry.Generator;

internal static class ProxyWriter
{
    public static string Write(InstrumentModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        // The <auto-generated> header exempts a file from analyzer diagnostics by convention,
        // but ErrorProne.NET analyses generated files anyway — so EPC12 reaches consumers.
        // It fires on the catch block below, which reads _ex.Message for the span status and
        // then rethrows with a bare `throw;`. Nothing is swallowed, so the diagnostic is a
        // false positive; suppressing it here spares every adopter their own <NoWarn>.
        // File-scoped, so it cannot leak into consumer-authored code.
        sb.AppendLine("#pragma warning disable EPC12 // catch reads _ex.Message for span status, then rethrows");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Diagnostics.Metrics;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // A nested interface's proxy is emitted next to it, inside partial declarations of its
        // containing types, so it can name the interface as the interface's siblings do.
        foreach (var containing in model.ContainingTypes)
        {
            sb.AppendLine(containing);
            sb.AppendLine("{");
        }

        var accessibility = model.PublicProxy ? "public" : "internal";
        sb.AppendLine($"{accessibility} sealed class {model.ProxyName}{model.TypeParameters} : {model.InterfaceName}");
        // The proxy is a new type, so a generic one repeats the interface's constraints.
        foreach (var clause in model.ConstraintClauses)
            sb.AppendLine($"    {clause}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly ActivitySource _activitySource = new({Literal(model.ActivitySourceName)});");
        sb.AppendLine($"    private static readonly Meter _meter = new({Literal(model.ActivitySourceName)});");

        var fields = MetricFieldTable.Build(model);
        WriteMetricFields(sb, fields);

        sb.AppendLine();
        WriteFieldsAndConstructor(sb, model);

        for (var i = 0; i < model.Methods.Count; i++)
            WriteMethod(sb, model.Methods[i], i, fields);

        sb.AppendLine("}");
        for (var i = 0; i < model.ContainingTypes.Count; i++)
            sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits the wrapped instance field, any resolved span-name fields, and the constructor.
    /// </summary>
    /// <remarks>
    /// Span names containing <c>{type}</c> vary by implementation, so they cannot be literals at
    /// the call site. They are resolved once in the constructor instead: the wrapped instance
    /// cannot change for the lifetime of the proxy, so the name is stable, and composing it here
    /// keeps the per-call path free of string concatenation.
    /// </remarks>
    private static void WriteFieldsAndConstructor(StringBuilder sb, InstrumentModel model)
    {
        sb.AppendLine($"    private readonly {model.InterfaceName} _inner;");

        var templated = model.Methods
            .Select((m, i) => (Method: m, Index: i))
            .Where(x => x.Method.TraceNameExpression is not null)
            .ToList();

        foreach (var (method, index) in templated)
            sb.AppendLine($"    private readonly string {SpanNameField(method, index)};");

        if (templated.Count == 0)
        {
            sb.AppendLine($"    public {model.ProxyName}({model.InterfaceName} inner) => _inner = inner;");
            return;
        }

        sb.AppendLine($"    public {model.ProxyName}({model.InterfaceName} inner)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        sb.AppendLine("        // Composed once per wrapped instance. Doing it per call would allocate a");
        sb.AppendLine("        // string on every invocation of an instrumented method.");
        sb.AppendLine("        var _implName = inner.GetType().Name;");
        foreach (var (method, index) in templated)
            sb.AppendLine($"        {SpanNameField(method, index)} = {method.TraceNameExpression};");
        sb.AppendLine("    }");
    }

    private static void WriteMetricFields(StringBuilder sb, MetricFieldTable fields)
    {
        foreach (var field in fields.Fields)
        {
            var (type, factory) = field.Kind == MetricKind.Counter
                ? ("Counter<long>", "CreateCounter<long>")
                : ("Histogram<double>", "CreateHistogram<double>");

            sb.AppendLine($"    private static readonly {type} {field.FieldName} = _meter.{factory}({FactoryArguments(field)});");
        }
    }

    /// <summary>
    /// Arguments to <c>CreateCounter</c>/<c>CreateHistogram</c>. Unit and description are named
    /// and only passed when set, so an instrument without them emits the same call as before.
    /// </summary>
    private static string FactoryArguments(MetricFieldTable.Field field)
    {
        var args = Literal(field.Metric);
        if (field.Unit is not null)
            args += ", unit: " + Literal(field.Unit);
        if (field.Description is not null)
            args += ", description: " + Literal(field.Description);

        return args;
    }

    /// <summary>
    /// Field holding a resolved <c>{type}</c> span name. Indexed as well as named, because
    /// overloads share a method name and would otherwise collide on one field.
    /// </summary>
    private static string SpanNameField(MethodModel method, int index) =>
        $"_spanName_{method.Name}_{index}";

    private static void WriteMethod(StringBuilder sb, MethodModel method, int index, MetricFieldTable fields)
    {
        sb.AppendLine();

        var asyncKeyword = method.IsAsync ? "async " : string.Empty;
        var paramList    = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {Id(p.Name)}"));
        var argList      = string.Join(", ", method.Parameters.Select(p => Id(p.Name)));

        sb.AppendLine($"    public {asyncKeyword}{method.ReturnType} {Id(method.Name)}{method.TypeParameters}({paramList})");
        // An implicit implementation of a generic method has to repeat its constraints.
        foreach (var clause in method.ConstraintClauses)
            sb.AppendLine($"        {clause}");
        sb.AppendLine("    {");

        if (method.TraceName is not null)
            WriteSpanStartAndTags(sb, method, index);

        if (method.Histogram is not null)
            sb.AppendLine("        var _sw = Stopwatch.GetTimestamp();");

        var needsTry = method.TraceName is not null
                    || method.Histogram is not null
                    || method.Count is not null
                    || method.ResultMetrics.Count > 0;

        if (needsTry)
            WriteInstrumentedBody(sb, method, argList, fields);
        else
            WritePassthroughBody(sb, method, argList);

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Starts the span and sets the tags that are known before the wrapped call runs.
    /// </summary>
    private static void WriteSpanStartAndTags(StringBuilder sb, MethodModel method, int index)
    {
        // A templated name was resolved against the wrapped instance in the constructor; a
        // constant one is emitted inline, so the common case stays a plain string literal.
        var spanName = method.TraceNameExpression is not null
            ? SpanNameField(method, index)
            : Literal(method.TraceName!);
        sb.AppendLine($"        using var _activity = _activitySource.StartActivity({spanName});");

        // Constants first: they identify which implementation is running, so they are the
        // most useful thing present if a sampler inspects tags at ActivityStarted.
        foreach (var constant in method.ConstantTags)
            sb.AppendLine($"        _activity?.SetTag({Literal(constant.TagName)}, {constant.Literal});");

        // Set immediately after the span starts so the tags are present for its whole
        // lifetime. `_activity?.` short-circuits the whole call when nothing sampled the
        // span, so an unsampled call neither evaluates nor boxes the argument.
        foreach (var p in method.Parameters)
        {
            if (p.TagName is null)
                continue;

            // Read from a copy when the access null-tests the argument: Roslyn would
            // otherwise treat the argument as maybe-null for the rest of the method, and it
            // is forwarded to the inner call — CS8604 in any consumer with nullable warnings.
            var source = Id(p.Name);
            if (p.TagNeedsCopy)
            {
                source = $"_tag_{p.Name}";
                sb.AppendLine($"        var {source} = {Id(p.Name)};");
            }

            var access = p.TagAccessSuffix is { } suffix
                ? source + suffix
                : source;

            sb.AppendLine($"        _activity?.SetTag({Literal(p.TagName)}, {access});");
        }
    }

    private static void WriteInstrumentedBody(StringBuilder sb, MethodModel method, string argList, MetricFieldTable fields)
    {
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        var awaitKeyword = method.IsAsync ? "await " : string.Empty;
        var callExpr     = $"{awaitKeyword}_inner.{Id(method.Name)}{method.TypeParameters}({argList})";

        if (method.ReturnsVoid)
            sb.AppendLine($"            {callExpr};");
        else
            sb.AppendLine($"            var _result = {callExpr};");

        // Tags and result-driven instruments read the result, so they come first and share one
        // null-state copy. [Count] and [Histogram] follow, guarded when they have a When. Each
        // tagged measurement numbers its tag list, so every local on the method is distinct.
        var tagLists = 0;
        if (!method.ReturnsVoid)
            WriteResultReads(sb, method, fields, ref tagLists);

        var root = method.ResultCanBeNull ? "_tagged" : "_result";

        if (method.Count is { } count)
        {
            WriteMeasurement(
                sb, method, count, fields, Guard(root, count.GuardExpression), "1", root, ref tagLists);
        }

        if (method.Histogram is { } histogram)
        {
            WriteMeasurement(
                sb, method, histogram, fields, Guard(root, histogram.GuardExpression),
                "Stopwatch.GetElapsedTime(_sw).TotalMilliseconds", root, ref tagLists);
        }

        if (!method.ReturnsVoid)
            sb.AppendLine("            return _result;");

        sb.AppendLine("        }");
        WriteCatchBlock(sb, method, fields);
    }

    /// <summary>
    /// Emits everything that reads the result: the result-derived tags, when there is a span to
    /// carry them, then the result-driven instruments in attribute order.
    /// </summary>
    /// <remarks>
    /// Member access goes through a copy of the result rather than the result itself. Roslyn
    /// treats <c>_result?.Member</c> as a null test on <c>_result</c>, which leaves it in a
    /// maybe-null state — and the following <c>return _result;</c> then raises CS8603 in any
    /// consumer with nullable warnings enabled. Testing the copy keeps the returned value's
    /// null-state intact while still guaranteeing instrumentation cannot throw on a null result.
    /// </remarks>
    private static void WriteResultReads(StringBuilder sb, MethodModel method, MetricFieldTable fields, ref int tagLists)
    {
        // Tags need a span to carry them; ZTEL004 reports a result tag without one.
        var tags = method.TraceName is not null
            ? method.ResultTags
            : EquatableArray<ResultTagModel>.Empty;

        // Every read that null-tests the result goes through the copy: a member access, a guard,
        // or a metric value, which is always read through the root. A guarded tag that records
        // the whole result still null-tests _result in its guard, so it needs the copy too.
        var needsCopy = method.ResultCanBeNull
            && (tags.Any(t => !string.IsNullOrEmpty(t.Member) || t.GuardExpression is not null)
                || method.ResultMetrics.Count > 0
                || method.MetricTags.Count > 0
                || method.Count?.GuardExpression is not null
                || method.Histogram?.GuardExpression is not null);

        if (needsCopy)
            sb.AppendLine("            var _tagged = _result;");

        var root = method.ResultCanBeNull ? "_tagged" : "_result";

        foreach (var tag in tags)
            WriteResultTag(sb, tag, root);

        for (var i = 0; i < method.ResultMetrics.Count; i++)
            WriteResultMetric(sb, method, method.ResultMetrics[i], i, root, fields, ref tagLists);
    }

    private static void WriteResultTag(StringBuilder sb, ResultTagModel tag, string root)
    {
        // No member records the result itself: no member access, so no null test and no
        // effect on _result's null-state. Otherwise the generator resolved the path, choosing
        // the operator for every segment, and reported ZTEL007 instead where it could not.
        var access = string.IsNullOrEmpty(tag.Member) ? "_result" : root + tag.AccessSuffix;

        if (tag.GuardExpression is { } guard)
        {
            // The guard has to prevent the member being read at all, which a null-conditional
            // cannot: `?.` protects against a null result, not against a result whose value is
            // unset. Reading Value on a failed Result is meaningless at best and throws at worst.
            sb.AppendLine($"            if ({root}{guard})");
            sb.AppendLine($"                _activity?.SetTag({Literal(tag.TagName)}, {access});");
        }
        else
        {
            sb.AppendLine($"            _activity?.SetTag({Literal(tag.TagName)}, {access});");
        }
    }

    /// <summary>
    /// Emits one <c>[CountFromResult]</c> or <c>[HistogramFromResult]</c>. <paramref name="index"/>
    /// numbers its pattern local, so each read on a method binds a distinct name.
    /// </summary>
    private static void WriteResultMetric(
        StringBuilder sb, MethodModel method, MetricModel metric, int index, string root, MetricFieldTable fields, ref int tagLists)
    {
        var access = root + metric.ValueAccess;
        var guard = metric.GuardExpression is { } g ? root + g : null;

        // A value that can be null is bound by a pattern: a null is skipped, and the local is
        // non-nullable, so it converts to long or double without a cast. The guard comes first
        // and short-circuits, so the member is not read at all when the guard is false.
        string? condition;
        string value;
        if (metric.ValueCanBeNull)
        {
            var local = "_read" + index.ToString(CultureInfo.InvariantCulture);
            var test = $"{access} is {{ }} {local}";
            condition = guard is null ? test : $"{guard} && {test}";
            value = local;
        }
        else
        {
            condition = guard;
            value = access;
        }

        if (metric.ValueIsDecimal)
            value = "(double)" + value;

        WriteMeasurement(sb, method, metric, fields, condition, value, root, ref tagLists);
    }

    /// <summary>The guard appended to the result root, or null when there is none.</summary>
    private static string? Guard(string root, string? guardExpression) =>
        guardExpression is null ? null : root + guardExpression;

    /// <summary>
    /// Emits one <c>Add</c> or <c>Record</c> of <paramref name="value"/>, under
    /// <paramref name="condition"/> when there is one, with the <c>[MetricTagFromResult]</c> tags
    /// that apply to the metric.
    /// </summary>
    /// <remarks>
    /// <para>
    /// With tags, the measurement is behind the instrument's <c>Enabled</c>, checked first. With
    /// no listener the call is skipped before the tag list is built, a member is read or a value
    /// is boxed, so the no-listener path stays allocation-free. Nothing that would have been
    /// recorded is lost: a disabled instrument drops every measurement anyway.
    /// </para>
    /// <para>
    /// Without tags the emitted code is exactly what it was before tags existed.
    /// </para>
    /// </remarks>
    private static void WriteMeasurement(
        StringBuilder sb,
        MethodModel method,
        MetricModel metric,
        MetricFieldTable fields,
        string? condition,
        string value,
        string root,
        ref int tagLists)
    {
        var field = fields.FieldFor(metric);
        var operation = metric.Kind == MetricKind.Counter ? "Add" : "Record";

        List<MetricTagModel>? tags = null;
        foreach (var tag in method.MetricTags)
        {
            if (tag.AppliesTo(metric))
                (tags ??= new List<MetricTagModel>()).Add(tag);
        }

        if (tags is null)
        {
            var call = $"{field}.{operation}({value});";
            if (condition is null)
            {
                sb.AppendLine($"            {call}");
            }
            else
            {
                sb.AppendLine($"            if ({condition})");
                sb.AppendLine($"                {call}");
            }

            return;
        }

        var index = (tagLists++).ToString(CultureInfo.InvariantCulture);
        var list = "_metricTags" + index;
        var enabled = field + ".Enabled";

        sb.AppendLine($"            if ({(condition is null ? enabled : enabled + " && " + condition)})");
        sb.AppendLine("            {");
        sb.AppendLine($"                var {list} = new TagList();");

        for (var k = 0; k < tags.Count; k++)
            WriteMetricTag(sb, tags[k], list, $"_metricTag{index}_{k.ToString(CultureInfo.InvariantCulture)}", root);

        sb.AppendLine($"                {field}.{operation}({value}, in {list});");
        sb.AppendLine("            }");
    }

    /// <summary>
    /// Adds one tag to <paramref name="list"/>. The guard comes first and short-circuits, so the
    /// member is not read when it is false. A null value is bound away by the pattern and adds no
    /// tag, as <c>Activity.SetTag</c> adds none for a null.
    /// </summary>
    private static void WriteMetricTag(StringBuilder sb, MetricTagModel tag, string list, string local, string root)
    {
        var access = root + tag.Access;
        var guard = Guard(root, tag.GuardExpression);

        string? condition;
        string value;
        if (tag.ValueCanBeNull)
        {
            var test = $"{access} is {{ }} {local}";
            condition = guard is null ? test : $"{guard} && {test}";
            value = local;
        }
        else
        {
            condition = guard;
            value = access;
        }

        var add = $"{list}.Add({Literal(tag.TagName)}, {value});";
        if (condition is null)
        {
            sb.AppendLine($"                {add}");
        }
        else
        {
            sb.AppendLine($"                if ({condition})");
            sb.AppendLine($"                    {add}");
        }
    }

    private static void WriteCatchBlock(StringBuilder sb, MethodModel method, MetricFieldTable fields)
    {
        // Only the span reads the exception. Declaring the variable otherwise raises CS0168 in
        // the generated file, and that fails every consumer building with TreatWarningsAsErrors.
        sb.AppendLine(method.TraceName is not null
            ? "        catch (Exception _ex)"
            : "        catch (Exception)");
        sb.AppendLine("        {");

        if (method.TraceName is not null)
            sb.AppendLine("            _activity?.SetStatus(ActivityStatusCode.Error, _ex.Message);");

        // A guarded histogram records only when its guard holds, and a throw leaves no result to
        // evaluate it against. An unguarded one records on both paths, as it always has.
        if (method.Histogram is { GuardExpression: null } histogram)
            sb.AppendLine($"            {fields.FieldFor(histogram)}.Record(Stopwatch.GetElapsedTime(_sw).TotalMilliseconds);");

        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
    }

    private static void WritePassthroughBody(StringBuilder sb, MethodModel method, string argList)
    {
        var awaitKeyword  = method.IsAsync ? "await " : string.Empty;
        var callExpr      = $"{awaitKeyword}_inner.{Id(method.Name)}{method.TypeParameters}({argList})";
        var returnKeyword = method.ReturnsVoid ? string.Empty : "return ";
        sb.AppendLine($"        {returnKeyword}{callExpr};");
    }

    /// <summary>A method or parameter name as an identifier: a keyword gets the verbatim <c>@</c> prefix.</summary>
    private static string Id(string name) => TypeDeclarations.Identifier(name);

    /// <summary>
    /// A name as a C# string literal, escaped the way the language writes it. A quote or a
    /// backslash in a metric, span or tag name would otherwise emit code that does not compile.
    /// </summary>
    private static string Literal(string value) =>
        Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
}
